### ISSUE TITLE
indexer-agent: Null value resolved for non-null field `paused`

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#1025]
graph-node v0.35.1
indexer-agent v0.21.5

This is a previously known issue reported as https://github.com/graphprotocol/indexer/issues/985, caused by https://github.com/graphprotocol/graph-node/issues/5550  for which a workaround was introduced in indexer-agent. The workaround for this has been prematurely removed from indexer-agent, as the latest released graph-node version does not yet have a fix for https://github.com/graphprotocol/graph-node/issues/5550 .

```
{"level":50,"time":1729002912326,"pid":1,"hostname":"indexer-agent-84658b4c4-4p4rr","name":"IndexerAgent","component":"GraphNode","err":{"type":"IndexerError","message":"Failed to query indexing status API","stack":"IndexerError: Failed to query indexing status API\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:179:12)\n    at GraphNode.subgraphDeploymentsAssignments (/opt/indexer/packages/indexer-common/dist/graph-node.js:153:51)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GraphNode.subgraphDeployments (/opt/indexer/packages/indexer-common/dist/graph-node.js:106:17)\n    at async retries (/opt/indexer/packages/indexer-common/dist/graph-node.js:69:37)\n    at async RetryOperation._fn (/opt/indexer/node_modules/p-retry/index.js:50:12)","code":"IE018","explanation":"https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie018","cause":{"type":"CombinedError","message":"[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`","stack":"CombinedError: [GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n[GraphQL] Null value resolved for non-null field `paused`\n    at makeResult (/opt/indexer/node_modules/@urql/core/dist/443c35ce.js:182:43)\n    at /opt/indexer/node_modules/@urql/core/dist/443c35ce.js:298:20\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"CombinedError","graphQLErrors":[{"message":"Null value resolved for non-null field `paused`"},{"message":"Null value resolved for non-null field `paused`"},{"message":"Null value resolved for non-null field `paused`"},{"message":"Null value resolved for non-null field `paused`"},{"message":"Null value resolved for non-null field `paused`"}],"response":{"size":0,"timeout":0}}},"msg":"Failed to query indexing status API"}
{"level":40,"time":1729002912326,"pid":1,"hostname":"indexer-agent-84658b4c4-4p4rr","name":"IndexerAgent","component":"GraphNode","attempt":5,"retriesLeft":6,"err":"Failed to query indexing status API","msg":"Indexing statuses could not be queried"}
```

**Comment by RdtBui** [comment]
This is happening to us as well.

**Comment by nate-staked** [comment]
Same here

**Comment by RdtBui** [comment]
Can confirm that the issue is gone with the new [v0.21.6-2](https://github.com/graphprotocol/indexer/releases/tag/v0.21.6-2)
