### ISSUE TITLE
Indexer service race condition between channel syncing and receiving payments?

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/indexer#112]
I've noticed this error in indexer-service. The only situations in which I can see this happening is if

* the indexer received a payment, sent a receipt back, but the gateway didn't receive it,
* the indexer received a request to sync channels (to recover stalled ones) followed by a payment maybe? 

My interpretation may be off, hence the question mark in the issue title.

```json
{
  "level": 50,
  "time": 1605537563565,
  "pid": 485,
  "hostname": "graph-indexerservice-0",
  "dbName": "graph-indexeragent-10",
  "walletVersion": "@statechannels/server-wallet@1.10.1",
  "reason": "it is not my turn",
  "type": "UpdateChannelError",
  "stack": "Error: it is not my turn\n    at ensureItIsMyTurn (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/handlers/update-channel.js:29:26)\n    at chain_ (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/fp-ts/lib/Either.js:236:38)\n    at /usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/fp-ts/lib/Either.js:316:63\n    at Object.pipe (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/fp-ts/lib/function.js:198:26)\n    at Object.updateChannel (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/handlers/update-channel.js:43:23)\n    at criticalCode (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:241:88)\n    at /usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/wallet/store.js:98:55\n    at time (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/metrics.js:55:22)\n    at /usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/metrics.js:45:72\n    at /usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/receipt-manager/node_modules/@statechannels/server-wallet/lib/src/wallet/store.js:98:20",
  "msg": "it is not my turn"
}
```

**Comment by fordN** [comment]
Old, closing.
