### ISSUE TITLE
Knex: Timeout acquiring a connection

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#150]
```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/root/graph-infra/indexer-1/node_modules/@statechannels/server-wallet/node_modules/knex/lib/client.js:348:26)
    at async listCompleted (/root/graph-infra/indexer-1/node_modules/@statechannels/server-wallet/node_modules/knex/lib/migrate/migration-list-resolver.js:12:3)
    at async Promise.all (index 1)
    at async Migrator.latest (/root/graph-infra/indexer-1/node_modules/@statechannels/server-wallet/node_modules/knex/lib/migrate/Migrator.js:64:29) {
  sql: undefined,
  bindings: undefined
}
```

It is crash looping 10/10 on indexer/master for me and I can't figure out if it's a misconfiguration on my side, or what's really happening.

Full crash log loop here: https://pastebin.com/f3K3AeuD

I've only seen this reported *once* in discord and the guy who had the issue said it was related to his DNS, yet it doesn't make sense looking at the error message.

**Comment by fordN** [comment]
Let me know if you've seen this recently @trader-payne.
