### ISSUE TITLE
Indexer-service state channel error messages - 'Error during pushMessage'

### ISSUE THREAD

**Issue by danenright** [graphprotocol/indexer#170]
This has been discussed within the indexers channel but not yet reported, adding an issue as suggested by @andrewgordstewart 

`[2020-12-21 00:37:54.123 +0000] ERROR     (997571 on node1): Error during pushMessage
    dbName: "indexerprod"
    walletVersion: "@statechannels/server-wallet@1.13.1"
    reason: "Error during pushMessage"
    data: {
      "thisWalletVersion": "@statechannels/server-wallet@1.13.1",
      "payloadWalletVersion": "@statechannels/server-wallet@1.13.1",
      "cause": {
        "reason": "Not in channel",
        "type": "StoreError"
      }
    }
    type: "PushMessageError"
    stack: "Error: Error during pushMessage\n    at SingleThreadedWallet.pushMessage (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:283:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async timeAsync (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/metrics.js:58:16)\n    at async MessagePort.<anonymous> (/usr/local/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/multi-threaded-wallet/worker.js:36:169)"`

[service1.log](https://github.com/graphprotocol/indexer/files/5726771/service1.log)

**Comment by LexPrime** [comment]
I am getting a lot of these errors 
```  headers: {
      "accept": "application/json, text/plain, */*",
      "content-type": "application/json",
      "user-agent": "axios/0.19.2",
      "content-length": "21277",
      "host": "104.238.222.165",
      "connection": "close"
    }
    err: {
      "type": "IndexerError",
      "message": "Failed to handle state channel message",
      "stack":
          IndexerError: Failed to handle state channel message
              at Object.indexerError (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/indexer-common/dist/errors.js:97:12)
              at /home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/dist/server/index.js:262:42
              at Generator.throw (<anonymous>)
              at rejected (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/dist/server/index.js:6:65)
      "code": "IE023",
      "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie023",
      "cause": {
        "type": "Error",
        "message": "Error during pushMessage",
        "stack":
            Error: Error during pushMessage
                at SingleThreadedWallet.pushMessage (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:283:19)
                at processTicksAndRejections (internal/process/task_queues.js:93:5)
                at async timeAsync (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/metrics.js:58:16)
                at async MessagePort.<anonymous> (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/multi-threaded-wallet/worker.js:36:169)
      }
    }
[2020-12-24 11:52:16.513 +0000] DEBUG (IndexerService/21686 on graph-indexer.darksiders-staking.com): POST /channel-messages-inbox 500 50 - 155.437 ms
    indexer: "0xBE9d7c691792937Ca7e2535652886ff390Cc5b86"
    operator: "0xE35C249f495C563E42D5822985158825Eb37e61e"
    component: "Server"
[2020-12-24 11:52:16.513 +0000] ERROR (21686 on graph-indexer.darksiders-staking.com): Error during pushMessage
    dbName: "mainnet_indexer1"
    walletVersion: "@statechannels/server-wallet@1.13.1"
    reason: "Error during pushMessage"
    data: {
      "thisWalletVersion": "@statechannels/server-wallet@1.13.1",
      "payloadWalletVersion": "@statechannels/server-wallet@1.13.1",
      "cause": {
        "reason": "Not in channel",
        "type": "StoreError"
      }
    }
    type: "PushMessageError"
    stack: "Error: Error during pushMessage\n    at SingleThreadedWallet.pushMessage (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:283:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async timeAsync (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/metrics.js:58:16)\n    at async MessagePort.<anonymous> (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/multi-threaded-wallet/worker.js:36:169)"
```
https://raw.githubusercontent.com/LexPrime/logs/main/ind_serv.log
