### ISSUE TITLE
Indexer-service IE023 "Failed to handle state channel message" and "Not in channel errors"

### ISSUE THREAD

**Issue by LexPrime** [graphprotocol/indexer#179]
I periodically receive these errors in batches from the state channel
```
 err: {
      "type": "IndexerError",
      "message": "Failed to handle state channel message",
      "stack":
          IndexerError: Failed to handle state channel message
              at Object.indexerError (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@graphprotocol/indexer-common/dist/errors.js:97:12)
              at /home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/dist/server/index.js:262:42
              at Generator.throw (<anonymous>)
              at rejected (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/dist/server/index.js:6:65)
      "code": "IE023",
      "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie023",
      "cause": {
        "type": "Error",
        "message": "Error during pushMessage",
        "stack":
            Error: Error during pushMessage
                at SingleThreadedWallet.pushMessage (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:283:19)
                at runMicrotasks (<anonymous>)
                at processTicksAndRejections (internal/process/task_queues.js:93:5)
                at async timeAsync (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/metrics.js:58:16)
                at async MessagePort.<anonymous> (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/multi-threaded-wallet/worker.js:36:169)
      }
    }
[2020-12-26 19:15:40.312 +0000] DEBUG (IndexerService/2751 on graph-indexer.darksiders-staking.com): POST /channel-messages-inbox 500 50 - 241.540 ms
    indexer: "0xBE9d7c691792937Ca7e2535652886ff390Cc5b86"
    operator: "0xE35C249f495C563E42D5822985158825Eb37e61e"
    component: "Server"
[2020-12-26 19:15:40.310 +0000] ERROR (2751 on graph-indexer.darksiders-staking.com): Error during pushMessage
    dbName: "mainnet_indexer1"
    walletVersion: "@statechannels/server-wallet@1.13.1"
    reason: "Error during pushMessage"
    data: {
      "thisWalletVersion": "@statechannels/server-wallet@1.13.1",
      "payloadWalletVersion": "@statechannels/server-wallet@1.13.1",
      "cause": {
        "reason": "Not in channel",
        "type": "StoreError"
      }
    }
    type: "PushMessageError"
    stack: "Error: Error during pushMessage\n    at SingleThreadedWallet.pushMessage (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/wallet.js:283:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async timeAsync (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/metrics.js:58:16)\n    at async MessagePort.<anonymous> (/home/lexprime/.nvm/versions/node/v14.9.0/lib/node_modules/@graphprotocol/indexer-service/node_modules/@statechannels/server-wallet/lib/src/wallet/multi-threaded-wallet/worker.js:36:169)"
```
https://raw.githubusercontent.com/LexPrime/logs/main/graph/ind_serv_26.12.20.log

**Comment by Jannis** [comment]
@LexPrime I think there should be one error message just before the "Error during pushMessage". Any chance you could dig that up?

**Comment by LexPrime** [comment]
Here is complete https://github.com/LexPrime/logs/blob/main/graph/ind_serv_19:12-26-12-20.log

**Comment by LexPrime** [comment]
Another one https://github.com/LexPrime/logs/blob/main/graph/ind_serv_20:31-26-12-20.log
