### ISSUE TITLE
Unintentional allocation

### ISSUE THREAD

**Issue by akme** [graphprotocol/indexer#180]
When I've started an allocation, it went successfully, but then I got an error message that I have not enough stake, but I run 1 parallelAllocation and looks like the agent wanted to start a second allocation, and if I had more stake it would create 2 allocations instead of one.
When we'll have more subgraphs we don't want an agent to make an additional unintentional allocation.
```
{"level":30,"time":1609239484720,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","active":[],"target":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Reconcile deployments"}
{"level":30,"time":1609239484720,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deploy":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"remove":[],"msg":"Deployment changes"}
{"level":30,"time":1609239484721,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","name":"indexer-agent/PMJsMUojSF","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"msg":"Index subgraph deployment"}
{"level":30,"time":1609239484721,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","name":"indexer-agent/PMJsMUojSF","msg":"Create subgraph name"}
{"level":30,"time":1609239484721,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","currentEpoch":15,"maxAllocationEpochs":28,"allocationLifetime":27,"active":[],"msg":"Reconcile allocations"}
{"level":20,"time":1609239484721,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","number":1,"deployments":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Deployments to reconcile allocations for"}
{"level":30,"time":1609239484722,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"epoch":15,"allocationAmount":"8604009.0","totalActiveAllocationAmount":"0.0","desiredNumberOfAllocations":1,"activeNumberOfAllocations":0,"activeAllocations":[],"msg":"Reconcile deployment allocations"}
{"level":30,"time":1609239484722,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"epoch":15,"desiredNumberOfAllocations":1,"allocationAmount":"8604009.0","msg":"No active allocations for deployment, creating some now"}
{"level":30,"time":1609239484725,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","name":"indexer-agent/PMJsMUojSF","msg":"Successfully created subgraph name"}
{"level":30,"time":1609239484725,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","name":"indexer-agent/PMJsMUojSF","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"msg":"Deploy subgraph deployment"}
{"level":30,"time":1609239484805,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","name":"indexer-agent/PMJsMUojSF","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"msg":"Successfully deployed subgraph deployment"}
{"level":30,"time":1609239484806,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"node":"index_node_0","msg":"Reassign subgraph deployment"}
{"level":30,"time":1609239485111,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"amountGRT":"8604009.0","epoch":"15","msg":"Allocate to subgraph deployment"}
{"level":20,"time":1609239485397,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"msg":"Obtain a unique Allocation ID"}
{"level":30,"time":1609239485861,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"indexer":"0xIndexerAddress","amount":"8604009.0","allocation":"0xbFE3403f142940aF7130E20F6A31C3e62A365c2a","price":{"type":"BigNumber","hex":"0x2386f26fc10000"},"msg":"Allocate"}
{"level":30,"time":1609239486815,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"action":"allocate","tx":"0x989257222b8f275c4a5a202bc8cc1e7731571a70690a3f2c43f8974ce6a01150","msg":"Transaction pending"}
{"level":30,"time":1609239792669,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"action":"allocate","tx":"0x989257222b8f275c4a5a202bc8cc1e7731571a70690a3f2c43f8974ce6a01150","blockNumber":11548529,"blockHash":"0x8d8a0c898555139a3cb88d7f0cc9bebf91d3dc862aae3b84694efc83062261c3","msg":"Transaction successfully included in block"}
{"level":30,"time":1609239792669,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"amountGRT":"8604009.0","allocation":"0xbFE3403f142940aF7130E20F6A31C3e62A365c2a","epoch":"15","msg":"Successfully allocated to subgraph deployment"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","claimable":[],"msg":"Claim rebate rewards"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","active":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"target":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Reconcile deployments"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deploy":[],"remove":[],"msg":"Deployment changes"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","currentEpoch":15,"maxAllocationEpochs":28,"allocationLifetime":27,"active":[],"msg":"Reconcile allocations"}
{"level":20,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","number":1,"deployments":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Deployments to reconcile allocations for"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"epoch":15,"allocationAmount":"8604009.0","totalActiveAllocationAmount":"0.0","desiredNumberOfAllocations":1,"activeNumberOfAllocations":0,"activeAllocations":[],"msg":"Reconcile deployment allocations"}
{"level":30,"time":1609239792670,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"epoch":15,"desiredNumberOfAllocations":1,"allocationAmount":"8604009.0","msg":"No active allocations for deployment, creating some now"}
{"level":30,"time":1609239793013,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"amountGRT":"8604009.0","epoch":"15","msg":"Allocate to subgraph deployment"}
{"level":50,"time":1609239793304,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","component":"Network","indexer":"0xIndexerAddress","operator":"0xIndexerAddress","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"amount":"8604009.0","err":{"type":"IndexerError","message":"Failed to allocate: insufficient free stake","stack":"IndexerError: Failed to allocate: insufficient free stake\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:97:12)\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:422:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","code":"IE013","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie013","cause":{"type":"Error","message":"Unable to allocate 8604009.0 GRT: indexer only has a free stake amount of 0.415772925510931958 GRT","stack":"Error: Unable to allocate 8604009.0 GRT: indexer only has a free stake amount of 0.415772925510931958 GRT\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:422:98)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}},"msg":"Failed to allocate"}
{"level":30,"time":1609239844829,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","claimable":[],"msg":"Claim rebate rewards"}
{"level":30,"time":1609239844829,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","active":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"target":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Reconcile deployments"}
{"level":30,"time":1609239844829,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deploy":[],"remove":[],"msg":"Deployment changes"}
{"level":30,"time":1609239844830,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","currentEpoch":15,"maxAllocationEpochs":28,"allocationLifetime":27,"active":[{"id":"0xbFE3403f142940aF7130E20F6A31C3e62A365c2a","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"createdAtEpoch":15}],"msg":"Reconcile allocations"}
{"level":20,"time":1609239844830,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","number":1,"deployments":[{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"}],"msg":"Deployments to reconcile allocations for"}
{"level":30,"time":1609239844831,"pid":1,"hostname":"c6e2c0633198","name":"IndexerAgent","deployment":{"bytes32":"0x31edcacc9a53bc8ab4be2eeb0d873409da4c4228cb2d60e4243bd3b4e8af7500","ipfsHash":"QmRhYzT8HEZ9LziQhP6JfNfd4co9A7muUYQhPMJsMUojSF"},"epoch":15,"allocationAmount":"8604009.0","totalActiveAllocationAmount":"8604009.0","desiredNumberOfAllocations":1,"activeNumberOfAllocations":1,"activeAllocations":[{"id":"0xIndexerAddress","createdAtEpoch":15,"amount":"8604009.0"}],"msg":"Reconcile deployment allocations"}```

**Comment by cryptovestor21** [comment]
[settle-allocate-insufficientStake-lifecycle.log](https://github.com/graphprotocol/indexer/files/5824609/settle-allocate-insufficientStake-lifecycle.log)
Discord discussion:

JannisToday at 14:57
That's not unexpected. The way the agent syncs and reconciles with the network is eventually consistent, which means that sometimes e.g. its free stake information or its allocation data are out of date and lead to it e.g. trying to re-allocate. It double-checks whether an allocation already exists to avoid allocating again; that can lead to error messages like the above.

I'd like for it to be a little less noisy and confusing in those situations. @cryptovestor | wavefive If you could attach logs around the closing, opening and re-opening to the above issue that'll help double-check that it really doesn't do anything that it shouldn't.
[settle-allocate-insufficientStake-lifecycle.log](https://github.com/graphprotocol/indexer/files/5824607/settle-allocate-insufficientStake-lifecycle.log)

**Comment by akme** [comment]
Upgraded to 0.10.0 agent and didn't get any of these.
