### ISSUE TITLE
error when opening allocations on v17: this.provider.getFeeData is not a function

### ISSUE THREAD

**Issue by mindstyle85** [graphprotocol/indexer#291]
Many, or most baremetal indexers, are getting this.provider.getFeeData is not a function error when trying to open a new allocation. 

The only solution at the moment is to uninstall the whole graph stack and all packages, then reinstall, while also clearing cache etc. It is painful. 

So i have two requests:

1. please post a fix for this issue, we are on mainnet, not on test env anymore..
2. make sure to test the release properly on testnet before launching it on mainnet where this causes many headaches to people

thank you.

**Comment by fordN** [comment]
Hey @mindstyle85. 
I've seen the error you mention on earlier versions of the software as well, so I'm not sure it's related to the v0.17.0 release.  
The v0.17.0 release was tested for several days on Testnet before cutting the release with no issues.  

Could you provide some detail around the steps you used to do the initial install that you saw the issue with?

**Comment by mindstyle85** [comment]
hey @fordN !

yeah it is not version specific, but for us it happened the first time.

So it has happened after a normal upgrade, so just npm install the packages and restart things. This is where it goes broke, because the upgrade somehow "screws" some of the npm packages or libraries.

The solution was to uninstall graph npm packages, uninstall npm and nodejs, clear all npm cache and delete all remaining npm directories. Then proceed with reinstalling it all.

I am not that technical so i am sure others can give you more exact info on what might get screwed with the npm package upgrades. Ionut from Chainnode says it is probably npm module incompatibility after upgrading.

Note that this is all baremetal, i am unsure if docker users have this issue.

**Comment by vincenttaglia** [comment]
I am getting this error in 0.16.0 and 0.17.0 from a fresh Ubuntu 20.04 minimal install with only the agent on the machine, so it isn't exclusive to 0.17.0. Also tried on 18.04 minimal and had the same error.

I currently can't get my bare metal testnet agent to register my indexer on-chain using any known configuration methods.

---------------------------

Steps to reproduce (starting from Ubuntu 20.04/18.04 minimal, mostly taken from [Graph Academy](https://docs.thegraph.academy/technical-documentation/testnet/graph-protocol-testnet-baremetal/4_deployandconfiguregraphindexerstack)):

`sudo apt update`

`sudo apt install git nano`

Allow root login:
`sudo nano /etc/ssh/sshd_config`

Remove lock-out command:
`sudo nano /root/.ssh/authorized_keys`

Login as root

Install node/npm:
`curl -sL https://deb.nodesource.com/setup_14.x | \sudo -E bash - && sudo apt install -y nodejs && sudo npm install -g npm@latest`

Install Rust:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
`source $HOME/.cargo/env`
`sudo apt-get install -y clang libpq-dev libssl-dev pkg-config build-essential`

Install indexer-agent:
`npm install -g @graphprotocol/indexer-agent@0.17.0`

Login as user

Run agent
`./graph-indexer-agent-startup.sh`

-----------------------------------------

Relevant error:
```
{"level":40,"time":1631058865789,"pid":11882,"hostname":"testnet-indexer-agent","name":"IndexerAgent","err":{"type":"IndexerError","message":"Unhandled promise rejection","stack":"IndexerError: Unhandled promise rejection\n    at Object.indexerError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@graphprotocol/indexer-common/dist/errors.js:139:12)\n    at process.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/commands/start.js:349:39)\n    at process.emit (events.js:400:28)\n    at process.emit (domain.js:470:12)\n    at processPromiseRejections (internal/process/promises.js:245:33)\n    at processTicksAndRejections (internal/process/task_queues.js:96:32)","code":"IE035","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie035","cause":{"type":"Error","message":"call revert exception (method=\"decimals()\", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.1.0)","stack":"Error: call revert exception (method=\"decimals()\", errorSignature=null, errorArgs=[null], reason=null, code=CALL_EXCEPTION, version=abi/5.1.0)\n    at Logger.makeError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/logger/lib/index.js:180:21)\n    at Logger.throwError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/logger/lib/index.js:189:20)\n    at Interface.decodeFunctionResult (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/abi/lib/interface.js:289:23)\n    at Contract.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/contracts/lib/index.js:329:56)\n    at step (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/ethers/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","reason":null,"code":"CALL_EXCEPTION","method":"decimals()","errorSignature":null,"errorArgs":[null],"address":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48","args":[],"transaction":{"data":"0x313ce567","to":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"}}},"msg":"Unhandled promise rejection"}
{"level":50,"time":1631058866130,"pid":11882,"hostname":"testnet-indexer-agent","name":"IndexerAgent","component":"Network","indexer":"0x8D6AAd22E56a3BabeFfcf7BB8c60Fe6547b4A1d2","operator":"0x489EbeBbf2A7e804B510Fd68e5dc4cA4c3090EcB","address":"0x8D6AAd22E56a3BabeFfcf7BB8c60Fe6547b4A1d2","url":"http://testnet.vincenttaglia.com:7600/","geoCoordinates":["39.09","-94.56"],"geoHash":"9yuy2hpeb","err":{"type":"IndexerError","message":"Failed to register indexer","stack":"IndexerError: Failed to register indexer\n    at Object.indexerError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@graphprotocol/indexer-common/dist/errors.js:139:12)\n    at Network.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/network.js:590:46)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/network.js:25:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","code":"IE012","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie012","cause":{"type":"TypeError","message":"this.provider.getFeeData is not a function","stack":"TypeError: this.provider.getFeeData is not a function\n    at Wallet.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:190:60)\n    at step (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)\n    at Object.next (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)\n    at /usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:23:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:19:12)\n    at Wallet.Signer.getFeeData (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:185:16)\n    at Wallet.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:298:55)\n    at step (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)\n    at Object.next (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)"}},"msg":"Failed to register indexer"}
IndexerError: Failed to register indexer
    at Object.indexerError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@graphprotocol/indexer-common/dist/errors.js:139:12)
    at Network.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/network.js:590:46)
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/network.js:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'IE012',
  explanation: 'https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie012',
  cause: TypeError: this.provider.getFeeData is not a function
      at Wallet.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:190:60)
      at step (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)
      at Object.next (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)
      at /usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:23:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:19:12)
      at Wallet.Signer.getFeeData (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:185:16)
      at Wallet.<anonymous> (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:298:55)
      at step (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:48:23)
      at Object.next (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/abstract-signer/lib/index.js:29:53)
}
```

**Comment by novy4** [comment]
@vincenttaglia you should try node v14.17.3

**Comment by fordN** [comment]
Closing. Let me know if any of you see this spring up again and I'll reopen the investigation.
