### ISSUE TITLE
Testnet network subgraph times out with HTTP 504 from hardcoded indexer-agent subgraphDeployments request

### ISSUE THREAD

**Issue by sduchesneau** [graphprotocol/indexer#292]
When deploying an indexer-agent on testnet, I noticed that the indexer-agent was failing to fetch the list of subgraphs deployments because of a HTTP 504 GATEWAY TIMEOUT error.
Example log that was repeating frequently on indexer-agent:
```
{"level":50,"time":1627652553377,"pid":1,"hostname":"9be2472ae0aa","name":"IndexerAgent","component":"Network","indexer":"0xc944E90C64B2c07662A292be6244BDf05Cda44a7","operator":"0x5EFdc1fC0E875FC276C673a290fBB09C9B0CC0e3","err":{"type":"IndexerError","message":"Failed to query subgraph deployments worth indexing","stack":"IndexerError: Failed to query subgraph deployments worth indexing\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:139:12)\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:314:46)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","code":"IE009","explanation":"https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie009","cause":{"type":"b","message":"[GraphQL] Request failed with status code 504","name":"CombinedError","graphQLErrors":[{"message":"Request failed with status code 504","extensions":{}}],"response":{"size":0,"timeout":0}}},"msg":"Failed to query subgraph deployments worth indexing"}
{"level":40,"time":1627652553377,"pid":1,"hostname":"9be2472ae0aa","name":"IndexerAgent","component":"Agent","msg":"Failed to obtain target deployments, trying again later"}
``` 

Digging a bit more showed me where the graphql code was being generated:
https://github.com/graphprotocol/indexer/blob/v0.16.0/packages/indexer-agent/src/network.ts#L357-L373

The code mentions that it should `// TODO: Paginate here to not miss any deployments`, but currently it asks for the first 1000 deployments.

Requesting this payload from https://gateway.testnet.thegraph.com/network using curl or another graphql query tool was also giving me the 504 error after about 1min.
On mainnet gateway, the same query takes less than a few hundred milliseconds. 

A proper solution could include:
1. fixing a possibly temporary issue with the back-end serving that network endpoint (postgres overloaded, missing indexes, etc.)
2. reducing the complexity of the query (without the 'indexerAllocations { }' lookup in the query, the query completes in a timely manner)
3. implementing proper pagination.

My current workaround is to reduce the number of requested entities to `100` instead of `1000`.

For example, to produce a fixed docker container:
```Dockerfile
FROM ghcr.io/graphprotocol/indexer-agent:v0.16.0
RUN sed -i 's/subgraphDeployments.first: 1000/subgraphDeployments(first: 100/' /opt/indexer/packages/indexer-agent/dist/network.js
```

and then I build and push this on a local repository to be used by my docker-compose.yml recipe.

I hope this info is useful to someone, let me know if there is an easy fix with suggested solution "1", or if you want help with proposed solutions 2 and 3.

**Comment by fordN** [comment]
Thanks for the report @sduchesneau! 

The timeout issue on network subgraph queries has been fixed on the latest release, v0.17.0, by implementing pagination.  Please give it a try when you get a chance and report back if it is not remedied as expected. 🙏
