### ISSUE TITLE
`indexer-agent` v0.17.0 GraphQL error when querying the network subgraph

### ISSUE THREAD

**Issue by aasseman** [graphprotocol/indexer#294]
I've been getting this issue since I upgraded to v0.17.0 (I added the 2 messages prior to the error for context):
```jsonl
{
  "level": 20,
  "time": 1628008263579,
  "pid": 1,
  "hostname": "indexer-agent-0",
  "name": "IndexerAgent",
  "component": "Network",
  "indexer": "0xB393Ff3CD1f70Fecf9cf8B67f27780FbEA0D084F",
  "operator": "0x2890D1b13894258ab3d477729D62D52B43754f9B",
  "queryProgress": {
    "lastId": "0xfb82e381d1e131f186a19c40d53358d6508f4ffa23868c383928840af308dcd1",
    "first": 10,
    "fetched": 170,
    "exhausted": false,
    "retriesRemaining": 10
  },
  "msg": "Query subgraph deployments"
}
{
  "level": 20,
  "time": 1628008296078,
  "pid": 1,
  "hostname": "indexer-agent-0",
  "name": "IndexerAgent",
  "component": "SyncingServer",
  "msg": "POST /network - - - - ms"
}
{
  "level": 40,
  "time": 1628008296095,
  "pid": 1,
  "hostname": "indexer-agent-0",
  "name": "IndexerAgent",
  "err": {
    "type": "IndexerError",
    "message": "Unhandled promise rejection",
    "stack": "IndexerError: Unhandled promise rejection\n at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:139:12)\n at process.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:362:39)\n at process.emit (events.js:321:20)\n at process.EventEmitter.emit (domain.js:482:12)\n at processPromiseRejections (internal/process/promises.js:209:33)\n at processTicksAndRejections (internal/process/task_queues.js:98:32)",
    "code": "IE035",
    "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie035",
    "cause": {
      "type": "Error",
      "message": "Invalid AST Node: \"query allocations($indexer: String!) {\\n indexer(id: $indexer) {\\n allocations(where: {status: Active}, orderDirection: desc, first: 1000) {\\n id\\n indexer {\\n id\\n }\\n allocatedTokens\\n createdAtBlockHash\\n createdAtEpoch\\n closedAtEpoch\\n subgraphDeployment {\\n id\\n stakedTokens\\n signalAmount\\n }\\n }\\n }\\n}\\n\".",
      "stack": "Error: Invalid AST Node: \"query allocations($indexer: String!) {\\n indexer(id: $indexer) {\\n allocations(where: {status: Active}, orderDirection: desc, first: 1000) {\\n id\\n indexer {\\n id\\n }\\n allocatedTokens\\n createdAtBlockHash\\n createdAtEpoch\\n closedAtEpoch\\n subgraphDeployment {\\n id\\n stakedTokens\\n signalAmount\\n }\\n }\\n }\\n}\\n\".\n at visit (/opt/indexer/node_modules/graphql/language/visitor.js:237:15)\n at Object.print (/opt/indexer/node_modules/graphql/language/printer.js:17:29)\n at NetworkSubgraph.<anonymous> (/opt/indexer/packages/indexer-common/dist/network-subgraph.js:122:71)\n at Generator.next (<anonymous>)\n at fulfilled (/opt/indexer/packages/indexer-common/dist/network-subgraph.js:5:58)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    }
  },
  "msg": "Unhandled promise rejection"
}
```

I am running the indexer stack using the official containers on Kubernetes (set-up based on the one from this repo).
The `indexer-agent` is using a locally synced network subgraph `Qmf5XXWA8zhHbdvWqtPcR3jFkmb5FLR4MAefEYx8E3pHfr`.

**Comment by aasseman** [comment]
Finally found the problem.
I had to: 
- Set `INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT="https://gateway.thegraph.com/network"` -- and not https://github.com/graphprotocol/indexer/blob/8c5da29200362cfefcb6ae2dd0348e7d6520dec4/k8s/base/indexer-service/statefulset.yaml#L55-L56
- Add `INDEXER_SERVICE_NETWORK_SUBGRAPH_DEPLOYMENT`, pointing to the correct IPFS hash. (I had it set only for the `indexer-agent` before, and it was fine).
