### ISSUE TITLE
Indexer 0.17.0 not able to Close and Open allocations with bigger size

### ISSUE THREAD

**Issue by begetan** [graphprotocol/indexer#298]
After upgrae of indexer-agent and indexer-service on the testnet I've also decided to change global rules configuration.  It was: 
`graph indexer rules set global allocationAmount 40000 parallelAllocations 5 decisionBasis always` 

And replaced by `graph indexer rules set global allocationAmount 100000 parallelAllocations 1 decisionBasis always` 

The Idea is to replace of 5 * 40 = 200k allocations with a singe 100k

Here is the message about processing of 4 expired allocations:

```json
{
  "level": 30,
  "time": 1628665848444,
  "pid": 1,
  "hostname": "8c320ebfc7af",
  "name": "IndexerAgent",
  "component": "Agent",
  "deployment": {
    "bytes32": "0x6f5c5b9b2bb184bca1d2f578b1df5526507d42943a189afe35d797c7a7ad0abf",
    "ipfsHash": "QmVqMeQUwvQ3XjzCYiMhRvQjRiQLGpVt8C3oHgvDi3agJ2"
  },
  "epoch": 3426,
  "number": 5,
  "expiredAllocations": [
    "0x5fD9b9008A774ECDc3E347539E9089C7023F0781",
    "0x9b4786795610E2417adE7e128f081b36f1b8B0f6",
    "0xB72a1150280952aDC365c24e5eA89294a6b163Cf",
    "0xcE93e54f901805bE1676Ad6Fc7C1e3AF8b8241e4",
    "0xf12F197da479A08933d542E34277249D2731ca6b"
  ],
  "msg": "Reallocating expired allocations"
}
```

 Next agent is trying to re-allocate it
 
 ```json
 {
  "level": 30,
  "time": 1628665849044,
  "pid": 1,
  "hostname": "8c320ebfc7af",
  "name": "IndexerAgent",
  "component": "Network",
  "indexer": "0x3ad34B9dFaEefaeD3CdB2C60Ea93EAe60463DedF",
  "operator": "0x8289Eed3c46C76099B7712fAA4b4bb902c739036",
  "allocation": "0x5fD9b9008A774ECDc3E347539E9089C7023F0781",
  "deployment": {
    "bytes32": "0x6f5c5b9b2bb184bca1d2f578b1df5526507d42943a189afe35d797c7a7ad0abf",
    "ipfsHash": "QmVqMeQUwvQ3XjzCYiMhRvQjRiQLGpVt8C3oHgvDi3agJ2"
  },
  "createdAtEpoch": 2951,
  "poi": "0x4f4ddda0f29e8517f9ee1f95ce232aadc1a98616b3959283047976e467a60ea2",
  "createdAtBlockHash": "0xff2f898f8df5e349595c3d1f9fa5c49fef1ff6dff4bcb44ad3658a69d7781f5b",
  "existingAllocationAmount": "40000.0",
  "newAllocationAmount": "100000.0",
  "epoch": "3426",
  "msg": "Reallocate to subgraph deployment"
}
```
And fails because there is not enought amount os free stake

```json
{
  "level": 50,
  "time": 1628665849347,
  "pid": 1,
  "hostname": "8c320ebfc7af",
  "name": "IndexerAgent",
  "component": "Network",
  "indexer": "0x3ad34B9dFaEefaeD3CdB2C60Ea93EAe60463DedF",
  "operator": "0x8289Eed3c46C76099B7712fAA4b4bb902c739036",
  "allocation": "0x5fD9b9008A774ECDc3E347539E9089C7023F0781",
  "deployment": {
    "bytes32": "0x6f5c5b9b2bb184bca1d2f578b1df5526507d42943a189afe35d797c7a7ad0abf",
    "ipfsHash": "QmVqMeQUwvQ3XjzCYiMhRvQjRiQLGpVt8C3oHgvDi3agJ2"
  },
  "createdAtEpoch": 2951,
  "poi": "0x4f4ddda0f29e8517f9ee1f95ce232aadc1a98616b3959283047976e467a60ea2",
  "createdAtBlockHash": "0xff2f898f8df5e349595c3d1f9fa5c49fef1ff6dff4bcb44ad3658a69d7781f5b",
  "amount": "100000.0",
  "err": {
    "type": "IndexerError",
    "message": "Failed to allocate: insufficient free stake",
    "stack": "IndexerError: Failed to allocate: insufficient free stake\n    at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:139:12)\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:854:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "code": "IE013",
    "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie013",
    "cause": {
      "type": "Error",
      "message": "Unable to allocate 100000.0 GRT: indexer only has a free stake amount of 7612.831799035164424149 GRT, plus 40000.0 GRT from the existing allocation",
      "stack": "Error: Unable to allocate 100000.0 GRT: indexer only has a free stake amount of 7612.831799035164424149 GRT, plus 40000.0 GRT from the existing allocation\n    at Network.<anonymous> (/opt/indexer/packages/indexer-agent/dist/network.js:854:98)\n    at Generator.next (<anonymous>)\n    at fulfilled (/opt/indexer/packages/indexer-agent/dist/network.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    }
  },
  "msg": "Failed to closeAndAllocate"
}
```

I suppose it should be some logic, which evaluate a total number of allocations and trying to close unnessesary

**Comment by begetan** [comment]
I set as a work around back the allocation size to 40k, but changed parrallel allocations to 1:
`graph indexer rules set global allocationAmount 40000 parallelAllocations 5 decisionBasis always`

Now I got 40 x 5 allocation, which is also weird. I expect it should reopen 1 and  close 4 remaining allocations

**Comment by fordN** [comment]
Thanks for the report @begetan.  The close and allocate functionality introduces some complexity in managing stake.   @chriswessels do you think you could take a look at this one this week?

**Comment by chriswessels** [comment]
Just to provide a public update: @fordN and I have spoken through this issue, and agreed that the challenge here is that `parallelAllocations` introduce many complexities into flows like `closeAndAllocate`, however `parallelAllocations` are a legacy artifact. Therefore what makes most sense is to remove `parallelAllocations` from the agent, rather than trying to solve for the complexity that they introduce. For now, I'd recommend not using `parallelAllocations` (always set it to `1`) since they provide zero benefit.

**Comment by begetan** [comment]
`parallelAllocations` set to 1 is not helping for existing deployments, because `closeAndAllocate` ignores the new value

**Comment by fordN** [comment]
Closing this since parallel allocations have been deprecated in the indexer-agent at this point. The indexer-agent will close allocations if needed to reach a parallelAllocations value of `1` for all of your subgraphs.
