### ISSUE TITLE
indexer-agent: Unable to sign the query response due to unavailable AllocationSigners

### ISSUE THREAD

**Issue by chriswessels** [graphprotocol/indexer#320]
Figment and Protofire have both been reporting issues serving queries from the gateway, with indexer-service presenting an error similar to the following:

```
[2021-10-13 23:05:42.064 +0000] ERROR (IndexerService/1 on indexer-service-56b8447df8-wqg76): Failed to handle paid query
    indexer: "0xb06071394531B63b0bac78f27e12dc2BEaA913E4"
    operator: "0x7A361DB89c9419699DEf3349b5F6F1cBA294267D"
    component: "Server"
    err: {
      "type": "IndexerError",
      "message": "Failed to process paid query",
      "stack":
          IndexerError: Failed to process paid query
              at Object.indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:139:12)
              at /opt/indexer/packages/indexer-service/dist/server/index.js:213:50
              at Generator.throw (<anonymous>)
              at rejected (/opt/indexer/packages/indexer-service/dist/server/index.js:6:65)
      "code": "IE032",
      "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie032",
      "cause": {
        "type": "Error",
        "message": "Unable to sign the query response attestation",
        "stack":
            Error: Unable to sign the query response attestation
                at QueryProcessor.<anonymous> (/opt/indexer/packages/indexer-service/dist/queries.js:60:31)
                at Generator.next (<anonymous>)
                at fulfilled (/opt/indexer/packages/indexer-service/dist/queries.js:5:58)
        "status": 500
      }
    }
```

Kuba from Figment tracked this down, finding that queries are being received from the gateways that don't have a corresponding signer in the AllocationSigner map. Furthermore, these queries are for allocations that have already been closed.

The AllocationSigner map is maintained by periodically querying the network subgraph for active allocations, and instantiating NativeAllocationSigners for these allocations. The polling query is defined here: https://github.com/graphprotocol/indexer/blob/main/packages/indexer-service/src/allocations.ts#L25

Currently the query only filters allocations that are Active, so on a fresh start of indexer-service, it will not instantiate signers for allocations that have been recently closed, but that the gateway may still be sending requests to the indexer for. In normal operation (i.e. without an indexer-service restart), the AllocationSignerMap does not flush out signers that were instantiated for now-closed allocations, so even as the polling query runs and those allocations drop out of the result set, the signers are still available for queries that come in.

 If this is indeed the issue, the fix may just be to widen the filter on the polling query, perhaps to include allocations If that's the case, then a potential fix might just be to widen the [query scope](https://github.com/graphprotocol/indexer/blob/bc0ac0d55afdecf6e4de65a10d7a346e693f0957/packages/indexer-service/src/allocations.ts#L43) to include recently closed allocations (maybe where closedAtEpoch >= currentEpoch - 1, assuming the gateway respects those bounds).

More complete information on the issue can be found in these diagnoses threads:
https://discord.com/channels/438038660412342282/898136504549904386/898137387656429579
https://discord.com/channels/438038660412342282/897959055488868373/897980447915663411

**Comment by chriswessels** [comment]
@jakubbujny I just amended my post, what I was describing happens in indexer-service, not indexer-agent. Apologies. Did you restart indexer-service at the same time?
