### ISSUE TITLE
Indexer-cli image build CI is failing

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#347]
https://github.com/graphprotocol/indexer/runs/4743420252?check_suite_focus=true

```error occurred: Command "ar" "cq" "/opt/indexer/node_modules/@graphprotocol/cost-model/native/target/debug/build/neon-sys-d3022e8942fee15a/out/libneon.a" "/opt/indexer/node_modules/@graphprotocol/cost-model/native/target/debug/build/neon-sys-d3022e8942fee15a/out/native/build/Debug/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit status: 1).
#20 116.9 
#20 116.9 
#20 116.9 warning: build failed, waiting for other jobs to finish...
#20 116.9 error: build failed
#20 116.9 neon ERR! cargo build failed
#20 116.9 
#20 116.9 Error: cargo build failed
#20 116.9     at Target.<anonymous> (/opt/indexer/node_modules/neon-cli/lib/target.js:98:27)
#20 116.9     at Generator.next (<anonymous>)
#20 116.9     at fulfilled (/opt/indexer/node_modules/neon-cli/lib/target.js:24:58)
#20 116.9     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#20 116.9 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#20 ERROR: process "/bin/sh -c yarn --frozen-lockfile --non-interactive --production=true" did not complete successfully: exit code: 1
------
 > [stage-1 12/15] RUN yarn --frozen-lockfile --non-interactive --production=true:
#20 116.9 warning: build failed, waiting for other jobs to finish...
#20 116.9 error: build failed
#20 116.9 neon ERR! cargo build failed
#20 116.9 
#20 116.9 Error: cargo build failed
#20 116.9     at Target.<anonymous> (/opt/indexer/node_modules/neon-cli/lib/target.js:98:27)
#20 116.9     at Generator.next (<anonymous>)
#20 116.9     at fulfilled (/opt/indexer/node_modules/neon-cli/lib/target.js:24:58)
#20 116.9     at processTicksAndRejections (node:internal/process/task_queues:96:5)
#20 116.9 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
Dockerfile.indexer-cli:58
--------------------
  56 |     
  57 |     # Install dependencies; exclude dev dependencies
  58 | >>> RUN yarn --frozen-lockfile --non-interactive --production=true
  59 |     RUN ln -s /opt/indexer/packages/indexer-cli/bin/graph-indexer /usr/bin/graph
  60 |     
--------------------
error: failed to solve: process "/bin/sh -c yarn --frozen-lockfile --non-interactive --production=true" did not complete successfully: exit code: 1```

**Comment by fordN** [comment]
Resolved in #329
