### ISSUE TITLE
indexer-cli requires "nan" dependency not defined in package.json

### ISSUE THREAD

**Issue by promaty** [graphprotocol/indexer#388]
When installing indexer-cli from scratch, it fails because of missing `nan` dependency.
```
  Error: Cannot find module 'nan'
  Require stack:
  - /home/linuxbrew/.linuxbrew/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model/native/target/debug/build/neon-sys-a3d6d0544eef4213/out/native/[eval]
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
      at Module.require (internal/modules/cjs/loader.js:974:19)
      at require (internal/modules/cjs/helpers.js:101:18)
      at [eval]:1:1
      at Script.runInThisContext (vm.js:134:12)
      at Object.runInThisContext (vm.js:310:38)
      at internal/process/execution.js:81:19
      at [eval]-wrapper:6:22
      at evalScript (internal/process/execution.js:80:60) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/linuxbrew/.linuxbrew/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model/native/target/debug/build/neon-sys-a3d6d0544eef4213/out/native/[eval]'
    ]
  }
  gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

Thus I have to install it first before installing the cli:

```
npm install -g nan
npm install -g @graphprotocol/graph-cli
npm install -g @graphprotocol/indexer-cli
```

**Comment by fordN** [comment]
@promaty I'm wondering if you experience the same issue if you use `yarn` instead of `npm`?  There are a few known `npm` compatibility issues we are debugging.

**Comment by promaty** [comment]
@fordN just tried using `yarn`, installation completes but it doesn't appear as `graph indexer` submodule
```
yarn global add @graphprotocol/graph-cli
yarn global add @graphprotocol/indexer-cli

graph indexer

  Sorry, didn't recognize that command!
  Type graph --help to view common commands.
```

If I continue using `npm` then it works again (`graph-cli` installed using `yarn`):
```
yarn global add @graphprotocol/graph-cli
npm install -g nan
npm install -g @graphprotocol/indexer-cli

graph indexer
Manage indexer configuration

  indexer                            Manage indexer configuration
  indexer connect                    Connect to indexer management API
  indexer cost                       Manage costing for subgraphs
  indexer cost get                   Get cost models and/or variables for one or all subgraphs
  indexer cost set model             Update a cost model
  indexer cost set variables         Update cost model variables
  indexer disputes                   Configure allocation POI monitoring
  indexer disputes get               Cross-check POIs submitted in the network
  indexer rules                      Configure indexing rules
  indexer rules clear (reset)        Clear one or more indexing rules
  indexer rules delete               Remove one or many indexing rules
  indexer rules get                  Get one or more indexing rules
  indexer rules maybe                Index a deployment based on rules
  indexer rules prepare (offchain)   Offchain index a deployment (and start indexing it if necessary)
  indexer rules set                  Set one or more indexing rules
  indexer rules start (always)       Always index a deployment (and start indexing it if necessary)
  indexer rules stop (never)         Never index a deployment (and stop indexing it if necessary)
  indexer status                     Check the status of an indexer
```
