### ISSUE TITLE
Failed to collect receipts in exchange for query fee voucher in v0.19.3

### ISSUE THREAD

**Issue by bleiva** [graphprotocol/indexer#436]
version: v0.19.3

I got this error with some allocations:

```
[2022-06-30 18:20:19.199 +0000] INFO (IndexerAgent/1 on indexer-agent-0): Collect receipts for allocation
    component: "AllocationReceiptCollector"
    allocation: "0x5738d23e10eCA20F9e48fC33F70a86C9b38Fe667"
    receipts: 94844
[2022-06-30 18:20:20.792 +0000] ERROR (IndexerAgent/1 on indexer-agent-0): Failed to collect receipts in exchange for an on-chain query fee voucher
    component: "AllocationReceiptCollector"
    allocation: "0x5738d23e10eCA20F9e48fC33F70a86C9b38Fe667"
    err: {
      "type": "IndexerError",
      "message": "Failed to collect receipts in exchange for query fee voucher",
      "stack":
          IndexerError: Failed to collect receipts in exchange for query fee voucher
              at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:143:12)
              at AllocationReceiptCollector.<anonymous> (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:266:147)
              at Generator.throw (<anonymous>)
              at rejected (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:6:65)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "code": "IE054",
      "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie054",
      "cause": {
        "message": "Request body larger than maxBodyLength limit",
        "name": "Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]",
        "stack":
            Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
                at RedirectableRequest.write (/opt/indexer/node_modules/follow-redirects/index.js:102:24)
                at RedirectableRequest.end (/opt/indexer/node_modules/follow-redirects/index.js:127:10)
                at dispatchHttpRequest (/opt/indexer/node_modules/axios/lib/adapters/http.js:401:11)
                at new Promise (<anonymous>)
                at httpAdapter (/opt/indexer/node_modules/axios/lib/adapters/http.js:48:10)
                at dispatchRequest (/opt/indexer/node_modules/axios/lib/core/dispatchRequest.js:58:10)
                at Axios.request (/opt/indexer/node_modules/axios/lib/core/Axios.js:108:15)
                at Axios.<computed> [as post] (/opt/indexer/node_modules/axios/lib/core/Axios.js:140:17)
                at Function.wrap [as post] (/opt/indexer/node_modules/axios/lib/helpers/bind.js:9:15)
                at AllocationReceiptCollector.<anonymous> (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:229:56)
        "config": {
          "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
          },
          "transformRequest": [
            null
          ],
          "transformResponse": [
            null
          ],
          "timeout": 0,
          "xsrfCookieName": "XSRF-TOKEN",
          "xsrfHeaderName": "X-XSRF-TOKEN",
          "maxContentLength": -1,
          "maxBodyLength": -1,
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/octet-stream",
            "User-Agent": "axios/0.26.1",
            "Content-Length": 10622548
          },
          "method": "post",
          "url": "https://gateway.thegraph.com/collect-receipts",
          "data": {}
        },
        "code": "ERR_FR_MAX_BODY_LENGTH_EXCEEDED",
        "status": null
      }
    }
```

**Comment by hopeyen** [comment]
Hey, I think this is the issue this [open PR](https://github.com/graphprotocol/indexer/pull/385) is trying to solve
