### ISSUE TITLE
No subgraph is syncing 

### ISSUE THREAD

**Issue by novy4** [graphprotocol/indexer#49]
Subgraph stopped to sync following by graphql output.

indexer-cli 0.1.4
indexeragent 0.2.5
indexerservice 0.2.5
node 14.9.0

Agent logs:
```
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]: (node:5117) UnhandledPromiseRejectionWarning: Error: timeout (requestBody={"0":123,"1":34,"2":109,"3":101,"4":116,"5":104,"6":111,"7":100,"8":34,"9":58,"10":34,"11":101,"12":116,"13":104,"14":95,"15":98,"16":108,"17":111,"18":99,"19":107,"20":78,"21":117,"22":109,"23":98,"24":101,"25":114,"26":34,"27":44,"28":34,"29":112,"30":97,"31":114,"32":97,"33":109,"34":115,"35":34,"36":58,"37":91,"38":93,"39":44,"40":34,"41":105,"42":100,"43":34,"44":58,"45":54,"46":54,"47":44,"48":34,"49":106,"50":115,"51":111,"52":110,"53":114,"54":112,"55":99,"56":34,"57":58,"58":34,"59":50,"60":46,"61":48,"62":34,"63":125}, requestMethod="POST", timeout=120000, url="https://rinkeby.infura.io/v3/4750ef1a3e47479a9fc7551d4705f737", code=TIMEOUT, version=web/5.0.4)
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]:     at Logger.makeError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/logger/lib/index.js:179:21)
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]:     at Timeout._onTimeout (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@ethersproject/web/lib/index.js:124:35)
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]:     at listOnTimeout (internal/timers.js:554:17)
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]:     at processTimers (internal/timers.js:497:7)
Sep 03 11:22:57 graph-indexer graph-indexer-agent[5117]: (node:5117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 30743)
```
Graph Node logs
 ```
Sep 02 10:43:32 graph-indexer graph-node[24726]: Sep 02 10:43:32.012 INFO Done processing Ethereum trigger, waiting_ms: 0, handler: handleSwap, total_ms: 16, trigger_type: Log, address: 0xc5be…f40c, signature: Swap(indexed address,uint256,uint256,uint256,uint256,indexed address), block_hash: 0x875f95672b2e8d71832a4c006070bcfaccc61be83aca57034a01cefae04ad2bb, block_number: 10780799, subgraph_id: QmXKwSEMirgWVn41nRzkT3hpUBw29cp619Gx58XW6mPhZP, component: SubgraphInstanceManager
```

To fix this issue I had to restart graph-node and graph-indexer-agent

**Comment by fordN** [comment]
Closing this issue which is stale at this point.  Please open another one if you run into problems again.
