### ISSUE TITLE
Outdated DAI contract address for testnet configuration

### ISSUE THREAD

**Issue by begetan** [graphprotocol/indexer#496]
According to the documentation https://github.com/graphprotocol/indexer/blob/main/docs/networks.md#indexer-agent-1

INDEXER_AGENT_DAI_CONTRACT should be set at address 0x9e7e607afd22906f7da6f1ec8f432d6f244278be which is on rinkeby testent

```
As a result there is an error message on the startup:
{
  "level": 40,
  "time": 1665086729332,
  "pid": 1,
  "hostname": "c4f421fbd881",
  "name": "IndexerAgent",
  "err": {
    "type": "IndexerError",
    "message": "Unhandled promise rejection",
    "stack": "IndexerError: Unhandled promise rejection\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:161:12)\n    at process.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:430:56)\n    at process.emit (node:events:527:28)\n    at process.emit (node:domain:475:12)\n    at emit (node:internal/process/promises:140:20)\n    at processPromiseRejections (node:internal/process/promises:274:27)\n    at processTicksAndRejections (node:internal/process/task_queues:97:32)",
    "code": "IE035",
    "explanation": "https://github.com/graphprotocol/indexer/blob/master/docs/errors.md#ie035",
    "cause": {
      "type": "Error",
      "message": "call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.1)",
      "stack": "Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.1)\n    at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:233:21)\n    at Logger.throwError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:242:20)\n    at Interface.decodeFunctionResult (/opt/indexer/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/lib/interface.js:389:23)\n    at Contract.<anonymous> (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:395:56)\n    at step (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:48:23)\n    at Object.next (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:29:53)\n    at fulfilled (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:20:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
      "reason": null,
      "code": "CALL_EXCEPTION",
      "method": "decimals()",
      "data": "0x",
      "errorArgs": null,
      "errorName": null,
      "errorSignature": null,
      "address": "0x9e7E607AFD22906f7dA6f1ec8f432d6f244278BE",
      "args": [],
      "transaction": {
        "data": "0x313ce567",
        "to": "0x9e7E607AFD22906f7dA6f1ec8f432d6f244278BE"
      }
    }
  },
  "msg": "Unhandled promise rejection"
}

```

It should be replaced with a Goerli contract address or removed

**Comment by fordN** [comment]
That error message can be ignored right now.  

Towards resolving this: We are working with the contracts team to strategize the approach on Goerli to fetching DAI-GRT rates.
