### ISSUE TITLE
indexer-cli didn't work v0.20.11

### ISSUE THREAD

**Issue by mattsu2020** [graphprotocol/indexer#595]
The following error occurred when starting indexer-cli version 0.20.11 and running graph indexer status.
The axios module does not seem to be included.

```
/opt/indexer/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Cannot find module 'axios'
Require stack:
- /opt/indexer/packages/indexer-common/dist/allocations/query-fees.js
- /opt/indexer/packages/indexer-common/dist/allocations/index.js
- /opt/indexer/packages/indexer-common/dist/actions.js
- /opt/indexer/packages/indexer-common/dist/index.js
- /opt/indexer/packages/indexer-cli/dist/actions.js
- /opt/indexer/packages/indexer-cli/dist/commands/indexer/actions/approve.js
- /opt/indexer/node_modules/gluegun/build/loaders/module-loader.js
- /opt/indexer/node_modules/gluegun/build/loaders/command-loader.js
- /opt/indexer/node_modules/gluegun/build/runtime/runtime.js
- /opt/indexer/node_modules/gluegun/build/domain/builder.js
- /opt/indexer/node_modules/gluegun/build/index.js
- /opt/indexer/packages/indexer-cli/dist/cli.js
- /opt/indexer/packages/indexer-cli/bin/graph-indexer
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:16:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js',
    '/opt/indexer/packages/indexer-common/dist/allocations/index.js',
    '/opt/indexer/packages/indexer-common/dist/actions.js',
    '/opt/indexer/packages/indexer-common/dist/index.js',
    '/opt/indexer/packages/indexer-cli/dist/actions.js',
    '/opt/indexer/packages/indexer-cli/dist/commands/indexer/actions/approve.js',
    '/opt/indexer/node_modules/gluegun/build/loaders/module-loader.js',
    '/opt/indexer/node_modules/gluegun/build/loaders/command-loader.js',
    '/opt/indexer/node_modules/gluegun/build/runtime/runtime.js',
    '/opt/indexer/node_modules/gluegun/build/domain/builder.js',
    '/opt/indexer/node_modules/gluegun/build/index.js',
    '/opt/indexer/packages/indexer-cli/dist/cli.js',
    '/opt/indexer/packages/indexer-cli/bin/graph-indexer'
  ]
}
```

**Comment by tilacog** [comment]
Thanks for reporting, @mattsu2020.
Could you provide more details on how to reproduce this issue?

Like:
- are you using docker? If so, which image tag?
- which node version was used?
- which OS?

**Comment by mattsu2020** [comment]
This is my environments.
・Docker version
Docker version 20.10.23, build 7155243
・index-cli Image 
　ghcr.io/graphprotocol/indexer-cli:v0.20.11
・graph-node image
   graphprotocol/graph-node:v0.29.0
・OS
5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

**Comment by tilacog** [comment]
I could reproduce this by building the `indexer-cli` image on current `main` and executing the provided binary:

```
graph@78713798bfac:/$ ./opt/indexer/packages/indexer-cli/bin/graph-indexer                                                                                                     
/opt/indexer/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Cannot find module 'axios'
Require stack:
- /opt/indexer/packages/indexer-common/dist/allocations/query-fees.js
- /opt/indexer/packages/indexer-common/dist/allocations/index.js
- /opt/indexer/packages/indexer-common/dist/actions.js
- /opt/indexer/packages/indexer-common/dist/index.js
- /opt/indexer/packages/indexer-cli/dist/actions.js
- /opt/indexer/packages/indexer-cli/dist/commands/indexer/actions/approve.js
- /opt/indexer/node_modules/gluegun/build/loaders/module-loader.js
- /opt/indexer/node_modules/gluegun/build/loaders/command-loader.js
- /opt/indexer/node_modules/gluegun/build/runtime/runtime.js
- /opt/indexer/node_modules/gluegun/build/domain/builder.js
- /opt/indexer/node_modules/gluegun/build/index.js
- /opt/indexer/packages/indexer-cli/dist/cli.js
- /opt/indexer/packages/indexer-cli/bin/graph-indexer
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:16:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js',
    '/opt/indexer/packages/indexer-common/dist/allocations/index.js',
    '/opt/indexer/packages/indexer-common/dist/actions.js',
    '/opt/indexer/packages/indexer-common/dist/index.js',
    '/opt/indexer/packages/indexer-cli/dist/actions.js',
    '/opt/indexer/packages/indexer-cli/dist/commands/indexer/actions/approve.js',
    '/opt/indexer/node_modules/gluegun/build/loaders/module-loader.js',
    '/opt/indexer/node_modules/gluegun/build/loaders/command-loader.js',
    '/opt/indexer/node_modules/gluegun/build/runtime/runtime.js',
    '/opt/indexer/node_modules/gluegun/build/domain/builder.js',
    '/opt/indexer/node_modules/gluegun/build/index.js',
    '/opt/indexer/packages/indexer-cli/dist/cli.js',
    '/opt/indexer/packages/indexer-cli/bin/graph-indexer'
  ]
}
```
