### ISSUE TITLE
First time automatic reallocations send "allocate" queue commands instead

### ISSUE THREAD

**Issue by trader-payne** [graphprotocol/indexer#599]
## Current behaviour and steps to reproduce:
Have an indexer with no open allocations.
Open allocations across X subgraphs
Wait for the allocations to expire
The agent queues "allocate" commands instead of "reallocate"
Nothing happens, only one log entry where it complains about the fact that the indexer doesn't have any free stake.
Actions don't fail, just keep dangling without any more errors.

Commands used:
```
graph indexer actions queue allocate QmWGXQeVv1jfU2puJAbSXXwLDW4gtd6fhf2D4R2cRP7qCK 100000
graph indexer actions queue allocate QmeGpvmEKqwf21YauM95vS6jsCDBjcXoa1KeQppde5tWbh 75000
graph indexer actions queue allocate QmeWfMioAVdipQoxM5WxjtpU3ySYt7aedCECYToST2Rfui 25000
graph indexer actions approve {85..87}
```

## Expected behaviour:
Agent should've sent "reallocate" commands instead.

## Workaround:
Actions cancel && restart the agent
After a restart, if the previous actions are cancelled, it will send the right "reallocate" queue commands and successfully close the allocations.

## Logs from boot:
```[08:58:42.015] INFO (IndexerAgent/1): Connect to database
    host: "postgres2"
    port: 5432
    database: "agent_db"
[08:58:42.067] DEBUG (IndexerAgent/1): Listening on port
    component: "MetricsServer"
    port: 7300
[08:58:42.086] INFO (IndexerAgent/1): Successfully connected to database
[08:58:42.086] INFO (IndexerAgent/1): Run database migrations
[08:58:42.102] DEBUG (IndexerAgent/1): Migrations status
    pending: []
    executed: [
      {
        "name": "00-cost-model-variables-jsonb.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/00-cost-model-variables-jsonb.js"
      },
      {
        "name": "01-reset-state-channels.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/01-reset-state-channels.js"
      },
      {
        "name": "02-remove-state-channels.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/02-remove-state-channels.js"
      },
      {
        "name": "03-poi-disputes-add-subgraph-deployment-id.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/03-poi-disputes-add-subgraph-deployment-id.js"
      },
      {
        "name": "03-rename-receipts-table.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/03-rename-receipts-table.js"
      },
      {
        "name": "04-rename-fee-columns.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/04-rename-fee-columns.js"
      },
      {
        "name": "05-indexing-rules-add-subgraph-id.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/05-indexing-rules-add-subgraph-id.js"
      },
      {
        "name": "06-indexing-rules-add-max-lifetime.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/06-indexing-rules-add-max-lifetime.js"
      },
      {
        "name": "07-indexing-rules-add-require-supported.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/07-indexing-rules-add-require-supported.js"
      },
      {
        "name": "08-indexing-rules-add-auto-renewal.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/08-indexing-rules-add-auto-renewal.js"
      },
      {
        "name": "09-actions-expand-failure-reason-varchar.js",
        "path": "/opt/indexer/packages/indexer-agent/dist/db/migrations/09-actions-expand-failure-reason-varchar.js"
      }
    ]
[08:58:42.105] INFO (IndexerAgent/1): Successfully ran database migrations
[08:58:42.105] INFO (IndexerAgent/1): Sync database models
[08:58:42.133] INFO (IndexerAgent/1): Successfully synced database models
[08:58:42.133] INFO (IndexerAgent/1): Connect to Network chain
    provider: "https://eth-goerli.nodereal.io/v1/key"
[08:58:42.533] INFO (IndexerAgent/1): Connected to network
    provider: "https://eth-goerli.nodereal.io/v1/key"
    pollingInterval: 4000
    network: {
      "name": "goerli",
      "chainId": 5,
      "ensAddress": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
    }
[08:58:42.535] INFO (IndexerAgent/1): Connect wallet
    network: "goerli"
    chainId: 5
[08:58:42.645] INFO (IndexerAgent/1): Connected wallet
[08:58:42.645] INFO (IndexerAgent/1): Connect to contracts
    network: "goerli"
    chainId: 5
    providerNetworkChainID: 5
[08:58:42.658] INFO (IndexerAgent/1): Successfully connected to contracts
    curation: "0xE59B4820dDE28D2c235Bd9A73aA4e8716Cb93E9B"
    disputeManager: "0x8c344366D9269174F10bB588F16945eb47f78dc9"
    epochManager: "0x03541c5cd35953CD447261122F93A5E7b812D697"
    gns: "0x065611D3515325aE6fe14f09AEe5Aa2C0a1f0CA7"
    rewardsManager: "0x1246D7c4c903fDd6147d581010BD194102aD4ee2"
    serviceRegistry: "0x7CF8aD279E9F26b7DAD2Be452A74068536C8231F"
    staking: "0x35e3Cb6B317690d662160d5d02A5b364578F62c9"
    token: "0x5c946740441C12510a167B447B7dE565C20b9E3C"
[08:58:42.660] INFO (IndexerAgent/1): Connect to network
[08:58:43.050] INFO (IndexerAgent/1): Network active
    component: "Network"
    indexer: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    operator: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
[08:58:43.053] INFO (IndexerAgent/1): Indexer and operator are identical, operator status granted
    component: "Network"
    indexer: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    operator: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
[08:58:43.054] INFO (IndexerAgent/1): Successfully connected to network
    restakeRewards: true
[08:58:43.060] INFO (IndexerAgent/1): Launch indexer management API server
[08:58:43.077] INFO (IndexerAgent/1): Begin monitoring the queue for approved actions to execute
[08:58:43.082] INFO (IndexerAgent/1): Successfully launched indexer management API server
[08:58:43.083] INFO (IndexerAgent/1): Monitor operator ETH balance (refreshes every 120s)
    component: "ETHBalanceMonitor"
[08:58:43.083] INFO (IndexerAgent/1): Launch syncing server
[08:58:43.084] INFO (IndexerAgent/1): Successfully launched syncing server
[08:58:43.086] INFO (IndexerAgent/1): Connect to Graph node(s)
    component: "Agent"
[08:58:43.086] INFO (IndexerAgent/1): Check if indexing status API is available
[08:58:43.093] DEBUG (IndexerAgent/1): Listening on port 8000
    component: "IndexerManagementServer"
[08:58:43.093] DEBUG (IndexerAgent/1): Listening on port 8002
    component: "SyncingServer"
[08:58:43.103] INFO (IndexerAgent/1): Successfully connected to indexing status API
    currentDeployments: [
      {
        "bytes32": "0xecc038ab46f92a93e3e0666b24617756c113b119321a32bf96bdcc0daf08a6c8",
        "ipfsHash": "QmeGpvmEKqwf21YauM95vS6jsCDBjcXoa1KeQppde5tWbh"
      },
      {
        "bytes32": "0x75ceeab8cabcf30b9fc9db3313843d4bc9a146d4cc62796ca6a072bfd6d4dfe0",
        "ipfsHash": "QmWGXQeVv1jfU2puJAbSXXwLDW4gtd6fhf2D4R2cRP7qCK"
      },
      {
        "bytes32": "0xf04b883ed3f800eaa1505cfbf66d8e483ddc5846909a32a358d1966b502c1599",
        "ipfsHash": "QmeWfMioAVdipQoxM5WxjtpU3ySYt7aedCECYToST2Rfui"
      }
    ]
[08:58:43.103] INFO (IndexerAgent/1): Connected to Graph node(s)
    component: "Agent"
[08:58:43.110] INFO (IndexerAgent/1): Register indexer
    component: "Network"
    indexer: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    operator: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    address: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    url: "https://index.testnet.stakesquid.com/"
    geoCoordinates: [
      "69.420",
      "69.420"
    ]
    geoHash: "vs36gtw0g"
[08:58:43.381] WARN (IndexerAgent/1): Unhandled promise rejection
    err: {
      "type": "IndexerError",
      "message": "Unhandled promise rejection",
      "stack":
          IndexerError: Unhandled promise rejection
              at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:169:12)
              at process.<anonymous> (/opt/indexer/packages/indexer-agent/dist/commands/start.js:400:56)
              at process.emit (node:events:527:28)
              at process.emit (node:domain:475:12)
              at emit (node:internal/process/promises:140:20)
              at processPromiseRejections (node:internal/process/promises:274:27)
              at processTicksAndRejections (node:internal/process/task_queues:97:32)
      "code": "IE035",
      "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie035",
      "cause": {
        "type": "Error",
        "message": "call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method=\"decimals()\", data=\"0x\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)",
        "stack":
            Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="decimals()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
                at Logger.makeError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:238:21)
                at Logger.throwError (/opt/indexer/node_modules/@ethersproject/logger/lib/index.js:247:20)
                at Interface.decodeFunctionResult (/opt/indexer/node_modules/@ethersproject/abi/lib/interface.js:388:23)
                at Contract.<anonymous> (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:395:56)
                at step (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:48:23)
                at Object.next (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:29:53)
                at fulfilled (/opt/indexer/node_modules/@ethersproject/contracts/lib/index.js:20:58)
                at processTicksAndRejections (node:internal/process/task_queues:96:5)
        "reason": null,
        "code": "CALL_EXCEPTION",
        "method": "decimals()",
        "data": "0x",
        "errorArgs": null,
        "errorName": null,
        "errorSignature": null,
        "address": "0x9e7E607AFD22906f7dA6f1ec8f432d6f244278BE",
        "args": [],
        "transaction": {
          "data": "0x313ce567",
          "to": "0x9e7E607AFD22906f7dA6f1ec8f432d6f244278BE"
        }
      }
    }
[08:58:43.480] INFO (IndexerAgent/1): Current operator ETH balance
    component: "ETHBalanceMonitor"
    balance: 0.3085024354339311
[08:58:43.782] INFO (IndexerAgent/1): Indexer already registered, operator status already granted
    component: "Network"
    indexer: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    operator: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    address: "0x0F6Feb3BA20c56E94CfbCD98339E99bcE629D912"
    url: "https://index.testnet.stakesquid.com/"
    geoCoordinates: [
      "69.420",
      "69.420"
    ]
    geoHash: "vs36gtw0g"
[08:58:43.784] DEBUG (IndexerAgent/1): Query subgraph deployments in batches of 10
    component: "NetworkMonitor"
[08:58:43.784] INFO (IndexerAgent/1): Waiting for network data before reconciling every 120s
    component: "Agent"
[08:58:43.921] DEBUG (IndexerAgent/1): Auto allocation management executes the batch if at least one requirement is met
    component: "ActionManager"
    currentBatchSize: 3
    meetsMinBatchSize: true
    oldestAffectedAllocationCreatedAtEpoch: 2165
    affectedAllocationExpiring: true
[08:58:43.921] INFO (IndexerAgent/1): Executing batch of approved actions
    component: "ActionManager"
    actions: [
      {
        "id": 72,
        "type": "allocate",
        "status": "approved",
        "priority": 0,
        "deploymentID": "QmeGpvmEKqwf21YauM95vS6jsCDBjcXoa1KeQppde5tWbh",
        "allocationID": null,
        "amount": "75000.0",
        "poi": null,
        "force": null,
        "source": "indexerAgent",
        "reason": "deployment:always",
        "createdAt": "2023-02-03T00:26:02.956Z",
        "updatedAt": "2023-02-03T00:26:02.956Z",
        "transaction": null,
        "failureReason": null
      },
      {
        "id": 71,
        "type": "allocate",
        "status": "approved",
        "priority": 0,
        "deploymentID": "QmWGXQeVv1jfU2puJAbSXXwLDW4gtd6fhf2D4R2cRP7qCK",
        "allocationID": null,
        "amount": "100000.0",
        "poi": null,
        "force": null,
        "source": "indexerAgent",
        "reason": "deployment:always",
        "createdAt": "2023-02-03T00:26:02.947Z",
        "updatedAt": "2023-02-03T00:26:02.947Z",
        "transaction": null,
        "failureReason": null
      },
      {
        "id": 70,
        "type": "allocate",
        "status": "approved",
        "priority": 0,
        "deploymentID": "QmeWfMioAVdipQoxM5WxjtpU3ySYt7aedCECYToST2Rfui",
        "allocationID": null,
        "amount": "25000.0",
        "poi": null,
        "force": null,
        "source": "indexerAgent",
        "reason": "deployment:always",
        "createdAt": "2023-02-03T00:26:02.937Z",
        "updatedAt": "2023-02-03T00:26:02.937Z",
        "transaction": null,
        "failureReason": null
      }
    ]
    note: "If actions were approved very recently they may be missing from this list but will still be taken"
[08:58:43.924] DEBUG (IndexerAgent/1): Validating action batch
    component: "AllocationManager"
    function: "validateActionBatch"
    size: 3
[08:58:44.213] ERROR (IndexerAgent/1): Failed to execute batch tx on staking contract: IndexerError: Failed to allocate: insufficient free stake
    component: "ActionManager"
[08:58:44.213] ERROR (IndexerAgent/1): Failed to execute batch of approved actions
    component: "ActionManager"
    error: {
      "code": "IE072",
      "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie072",
      "cause": {
        "code": "IE013",
        "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie013",
        "cause": "Unfeasible action batch: Approved action batch GRT balance is 200000.0 but available stake equals 8225.2277965860652539."
      }
    }
[08:58:48.386] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]
[08:58:57.644] DEBUG (IndexerAgent/1): Execute 'actions' query
    component: "IndexerManagementClient"
    filter: {}
    orderBy: "id"
    orderDirection: "desc"
[08:58:57.655] DEBUG (IndexerAgent/1): POST / 200 30827 - 16.929 ms
    component: "IndexerManagementServer"
[08:58:59.401] DEBUG (IndexerAgent/1): Finished fetching subgraph deployments published to network
    component: "NetworkMonitor"
    publishedSubgraphs: 619
[08:58:59.421] INFO (IndexerAgent/1): Reconcile with the network
    component: "Agent"
    networkLatestEpoch: {
      "networkID": "eip155:5",
      "epochNumber": 2169,
      "startBlockNumber": 8425951,
      "startBlockHash": "0xfb0f82273cb1e29aea1c6d679620cad181ce18889f6eaf42e54270d6aa50b5cd",
      "latestBlock": 8426033
    }
[08:58:59.422] DEBUG (IndexerAgent/1): Execute 'actions' query
    component: "IndexerManagementClient"
    filter: {
      "status": "approved"
    }
[08:58:59.423] INFO (IndexerAgent/1): There are 3 approved actions awaiting execution, will reconcile with the network once they are executed
    component: "Agent"
[08:59:18.345] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]
[08:59:48.518] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]
[09:00:18.446] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]
[09:00:43.469] INFO (IndexerAgent/1): Current operator ETH balance
    component: "ETHBalanceMonitor"
    balance: 0.3085024354339311
[09:00:48.357] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]
[09:01:18.537] INFO (IndexerAgent/1): Query vouchers below the redemption threshold
    component: "AllocationReceiptCollector"
    hint: "If you would like to redeem vouchers like this, reduce the voucher redemption threshold"
    voucherRedemptionThreshold: "200.0"
    belowThresholdCount: 15
    totalValueGRT: "0.065761995608207981"
    allocations: [
      "0xd0815268fb88cA3f91Acc8ec2d888346372e327b",
      "0xba4cBE8c20f641141DEaDe861e638365804941e7",
      "0x0A0725a75B661F11f3B9639eeF104d442ca6E011",
      "0xA315a011ce600eF5BFBf8791fB138127d004558f",
      "0xc4452f7B57DA24F49CD9381a4aE18DFBAC5F0AAb",
      "0x2D2B4848Fc31284D7323EA8575449971c2049662",
      "0x350f2c4D91BeaE76c9759cD24e7E63f690301d9C",
      "0xF802DAeB8a1C3828772991E39060a251947ba8ED",
      "0x3098a7C890Af27cEEe9Fc4b7CA2Cd37Cd55EA545",
      "0x443ddabB96607F329297214dB40681CBa53349eb",
      "0xE61c70E34753bBA7BE31aC1d4E1Fc732842CA19E",
      "0x1D1B189A4560F8FA35766a8aDd1B082622909800",
      "0x4748803F7D6fb5A93068AFdD82a7CeC9E78D92Cb",
      "0x01b7BfF457f8D74Fbe1e5eFb6bBE65578c2C8932",
      "0x13BB44421D780C6Bed8BCC7a463276Cf10D89fF1"
    ]```

**Comment by trader-payne** [comment]
This is 10/10 reproducing every time:


Before restart:
Logs: https://pastebin.com/raw/QLJrx5Uk

<img width="1215" alt="Screenshot 2023-02-04 at 11 58 31" src="https://user-images.githubusercontent.com/10525363/216760961-0cfad467-d89a-4f92-a92e-f0bb287d628e.png">

Cancel rules and restart:
Logs: https://pastebin.com/raw/L6sNCc34

<img width="1215" alt="Screenshot 2023-02-04 at 12 02 19" src="https://user-images.githubusercontent.com/10525363/216761101-da4912da-0139-480e-a79f-373aa4e105f0.png">


Looking at the logs, I can see this - might be helpful:
Before restart:
```
[01:17:03.848] DEBUG (IndexerAgent/1): Execute 'queueActions' mutation
    component: "IndexerManagementClient"
    actions: [
      {
        "status": "approved",
        "type": "allocate",
        "deploymentID": "QmWGXQeVv1jfU2puJAbSXXwLDW4gtd6fhf2D4R2cRP7qCK",
        "amount": "100000.0",
        "source": "indexerAgent",
        "reason": "deployment:always",
        "priority": 0
      }
    ]
```

After restart:
```
[10:00:11.892] DEBUG (IndexerAgent/1): Execute 'queueActions' mutation
    component: "IndexerManagementClient"
    actions: [
      {
        "status": "approved",
        "type": "reallocate",
        "deploymentID": "QmeGpvmEKqwf21YauM95vS6jsCDBjcXoa1KeQppde5tWbh",
        "allocationID": "0xA293B2e807d091080A133Feec885fA488c7c6e5e",
        "amount": "75000.0",
        "source": "indexerAgent",
        "reason": "deployment:always:allocationExpiring",
        "priority": 0
      }
    ]
   
```
Notice the lines:
```
        "reason": "deployment:always",
```
vs
```
        "reason": "deployment:always:allocationExpiring",
```

**Comment by fordN** [comment]
Thanks for the detailed report, @trader-payne! 🙏 

### Hypothesis
In the indexer-agent reconciliation loop; the agent polls the subgraph to gather the data it needs and then it reconciles any needed changes in deployments or allocations.  I'll focus on the data it uses in relation to this case: for allocations and reallocations: active deployments on the indexer stack, active allocations on the network, and indexing rules.  
- The agent looks at the indexing rules and resolves them into an array of `networkDeploymentAllocationDecisions`: to allocate or not to allocate. 
https://github.com/graphprotocol/indexer/blob/71110cad4a26675344e07da15e1d63cdbad457f8/packages/indexer-agent/src/agent.ts#L263-L283
- The agent polls every 2 minutes for all of the indexers `activeAllocations`. 
https://github.com/graphprotocol/indexer/blob/71110cad4a26675344e07da15e1d63cdbad457f8/packages/indexer-agent/src/agent.ts#L326-L334
- The agent uses the `networkDeploymentAllocationDecisions` and `activeAllocations` to identify and queue up any actions that need to be taken (allocate, reallocate or unallocate). It does so for each item in the `networkDeploymentAllocationDecisions` array. For `networkAllocationDecision`s with `toAllocate` = `true`: the agent queues up an `allocation` action if there is no match in the `activeAllocations` array, otherwise if there is already an existing allocation it evaluates whether that allocation is expiring and needs a `reallocate` action. https://github.com/graphprotocol/indexer/blob/71110cad4a26675344e07da15e1d63cdbad457f8/packages/indexer-agent/src/agent.ts#L796-L825

In the last step, if the `activeAllocations` array incorrectly does not include an existing, active allocation for the deployment in question the agent will queue up an `allocate` action. This could be due to the network subgraph being behind, the network subgraph having a data issue, or simply because the activeAllocations array hasn't been refreshed recently enough to take into account a new allocation.   

I think it's worth digging in further to identify which of these causes is leading to this observed behavior; however, regardless of which it is I have an idea to improve robustness of this code path.  Idea: query for an active allocation within `reconcileDeploymentAllocationAction()` in order to be sure the agent has the most recent data available rather than continuing to rely just on the `activeAllocations` array gathered at the start of the reconciliation loop. 

### Questions
- What are you using for your network subgraph data source? Local subgraph, hosted-service api endpoint, gateway /network path?
- Since it appears to be not too difficult to reproduce, if you could reproduce with log level set to `trace` that would provide some helpful data to confirm (or deny) my hypothesis such as this log.https://github.com/graphprotocol/indexer/blob/71110cad4a26675344e07da15e1d63cdbad457f8/packages/indexer-agent/src/agent.ts#L867-L878. 

### Next steps
- [ ] Improve robustness by querying for an existing allocation within `reconcileDeploymentAllocationAction()` or its parent, `reconcileActions()`
- [ ] Continue to gather data to confirm the cause of the issue
