### ISSUE TITLE
indexer-agent: Failed to run database migrations after update 0.20.15

### ISSUE THREAD

**Issue by ThomasBlock** [graphprotocol/indexer#646]
I was running 0.20.12 on goerli, opened fantom allocations but learned that in order to close them i need the new version. 

So i updated  indexer-service, indexer-agent, indexer-cli to newest version 0.20.15 through npm install

But now i can no longer start the agent. The only hint i found on discord was to `drop table transfer_receipts ` , but this does not help for me. ( https://discord.com/channels/438038660412342282/807005869836861461/842157900671746048 ). And yes i probably started the service before the agent. So how could i recover my setup?

```
Started Graph Agent.
{"level":20,"time":1681625151400,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","component":"MetricsServer","component":"MetricsServer","port":7301,"msg":"Listening on port"}
{"level":30,"time":1681625151412,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","provider":"http://xxx:8545","msg":"Connect to Network chain"}
{"level":30,"time":1681625151431,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","provider":"http://xxx:8545/","pollingInterval":4000,"network":{"name":"goerli","chainId":5,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"msg":"Connected to network"}
{"level":30,"time":1681625151434,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","network":"goerli","chainId":5,"providerNetworkChainID":5,"msg":"Connect to contracts"}
{"level":30,"time":1681625151434,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","network":"goerli","chainId":5,"msg":"Connect wallet"}
{"level":30,"time":1681625151668,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Connected wallet"}
{"level":30,"time":1681625151700,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","curation":"0xE59B4820dDE28D2c235Bd9A73aA4e8716Cb93E9B","disputeManager":"0x8c344366D9269174F10bB588F16945eb47f78dc9","epochManager":"0x03541c5cd35953CD447261122F93A5E7b812D697","gns":"0x065611D3515325aE6fe14f09AEe5Aa2C0a1f0CA7","rewardsManager":"0x1246D7c4c903fDd6147d581010BD194102aD4ee2","serviceRegistry":"0x7CF8aD279E9F26b7DAD2Be452A74068536C8231F","staking":"0x35e3Cb6B317690d662160d5d02A5b364578F62c9","token":"0x5c946740441C12510a167B447B7dE565C20b9E3C","msg":"Successfully connected to contracts"}
{"level":30,"time":1681625151701,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","host":"xxx","port":5432,"database":"agent","msg":"Connect to database"}
{"level":30,"time":1681625151821,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Successfully connected to database"}
{"level":30,"time":1681625151821,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Run database migrations"}
{"level":20,"time":1681625151862,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","pending":[{"name":"11-update-deployment-names.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/11-update-deployment-names.js"}],"executed":[{"name":"00-cost-model-variables-jsonb.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/00-cost-model-variables-jsonb.js"},{"name":"01-reset-state-channels.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/01-reset-state-channels.js"},{"name":"02-remove-state-channels.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/02-remove-state-channels.js"},{"name":"03-poi-disputes-add-subgraph-deployment-id.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/03-poi-disputes-add-subgraph-deployment-id.js"},{"name":"03-rename-receipts-table.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/03-rename-receipts-table.js"},{"name":"04-rename-fee-columns.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/04-rename-fee-columns.js"},{"name":"05-indexing-rules-add-subgraph-id.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/05-indexing-rules-add-subgraph-id.js"},{"name":"06-indexing-rules-add-max-lifetime.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/06-indexing-rules-add-max-lifetime.js"},{"name":"07-indexing-rules-add-require-supported.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/07-indexing-rules-add-require-supported.js"},{"name":"08-indexing-rules-add-auto-renewal.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/08-indexing-rules-add-auto-renewal.js"},{"name":"09-actions-expand-failure-reason-varchar.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/09-actions-expand-failure-reason-varchar.js"},{"name":"10-indexing-rules-add-safety.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/10-indexing-rules-add-safety.js"}],"msg":"Migrations status"}
{ event: 'migrating', name: '11-update-deployment-names.js' }
{"level":20,"time":1681625151883,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0x954d1e40dd397aa4e46ba8f51d9eee3ac5051cb69da663350db71d444cc5b83d"}
{"level":20,"time":1681625151885,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0xce0cf8d178a6a76cbf539d24397c8e6bd7a755c114e032903eac3bdfa3efad30"}
{"level":20,"time":1681625151885,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0x0e54a37dd09c43927dd5b62a66a9b2024aeec11c307e4f47507cc20e28a019aa"}
{"level":20,"time":1681625151885,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0x92b5d8d908b390a10480d1f4c400532545649d774a09dadca779fd8f81353938"}
{"level":20,"time":1681625151885,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0x113fbabb4552ffafa3e57656002a947ac08304e1e32bc8492829170dfcc8c5f9"}
{"level":20,"time":1681625151886,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","msg":"Querying the Network Subgraph for more details on subgraph deployment 0xd971835ccda85c01dc273e8944658546919f85aeae866afae4ddf85acee1f0df"}
{"level":60,"time":1681625151912,"pid":103080,"hostname":"thegraph-goerli","name":"IndexerAgent","err":{"cause":{"jse_cause":{"jse_cause":{"message":"(0 , indexer_common_1.formatDeploymentName) is not a function","stack":"TypeError: (0 , indexer_common_1.formatDeploymentName) is not a function\n    at /usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/11-update-deployment-names.js:105:64\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/11-update-deployment-names.js:28:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","type":"TypeError"},"jse_info":{},"jse_shortmsg":"Original error","message":"Original error: (0 , indexer_common_1.formatDeploymentName) is not a function","name":"VError","stack":"VError: Original error: (0 , indexer_common_1.formatDeploymentName) is not a function\n    at Function.wrap (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:22:20)\n    at new MigrationError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:33:32)\n    at /usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:154:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Umzug.runCommand (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:110:20)","type":"VError"},"jse_info":{"context":{"graphNodeAdminEndpoint":"http://localhost:8020/","indexingStatusResolver":{"logger":"[Object]","statuses":"[Object]"},"logger":{"inner":"[Object]","options":"[Object]"},"networkMonitor":{"contracts":"[Object]","epochSubgraph":"[Object]","ethereum":"[Object]","indexer":"0xb273B5dB7E82ee8cfD306Ad36120563706B79692","indexingStatusResolver":"[Object]","logger":"[Object]","networkCAIPID":"eip155:5","networkSubgraph":"[Object]"},"queryInterface":{"queryGenerator":"[Object]","sequelize":"[Object]"}},"direction":"up","name":"11-update-deployment-names.js","path":"/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/db/migrations/11-update-deployment-names.js"},"jse_shortmsg":"Migration 11-update-deployment-names.js (up) failed","message":"Migration 11-update-deployment-names.js (up) failed: Original error: (0 , indexer_common_1.formatDeploymentName) is not a function","name":"MigrationError","stack":"MigrationError: Migration 11-update-deployment-names.js (up) failed: Original error: (0 , indexer_common_1.formatDeploymentName) is not a function\n    at /usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:154:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Umzug.runCommand (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/umzug/lib/umzug.js:110:20)","type":"MigrationError"},"code":"IE001","explanation":"https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie001","message":"Failed to run database migrations","stack":"IndexerError: Failed to run database migrations\n    at indexerError (/usr/lib/node_modules/@graphprotocol/indexer-agent/node_modules/@graphprotocol/indexer-common/dist/errors.js:171:12)\n    at /usr/lib/node_modules/@graphprotocol/indexer-agent/dist/commands/start.js:507:56\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/lib/node_modules/@graphprotocol/indexer-agent/dist/commands/start.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","type":"IndexerError"},"msg":"Failed to run database migrations"}
agent.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by tilacog** [comment]
Thanks for the report, @ThomasBlock.
This looks like a bug in the release. 

That migration should not be contained in the v0.20.15 package.
We will publish a new release soon.

**Comment by tilacog** [comment]
We just released a v0.20.16 that addresses this issue.

Closing this for now, but please let us know if it doesn't work as expected.
