### ISSUE TITLE
Voucher collection payload is too large

### ISSUE THREAD

**Issue by madumas** [graphprotocol/indexer#653]
Indexer-agent will split receipts into 25k batches for partial collection, but this 25k batch is too large and needs to be made smaller.

25k receipts weights 2 800 020 bytes, which is too large for the gateway endpoint

```
{
[...]
  "component": "AllocationReceiptCollector",
  "allocation": "0x7C3Ed9ab016ff40077c98Ceb54eE420E193c8849",
  "err": {
    "type": "IndexerError",
    "message": "Failed to collect receipts in exchange for query fee voucher",
    "stack": "IndexerError: Failed to collect receipts in exchange for query fee voucher\n    at indexerError (/opt/indexer/packages/indexer-common/dist/errors.js:169:12)\n    at AllocationReceiptCollector.<anonymous> (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:298:147)\n    at Generator.throw (<anonymous>)\n    at rejected (/opt/indexer/packages/indexer-common/dist/allocations/query-fees.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "code": "IE054",
    "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie054",
    "cause": {
      "message": "Request failed with status code 413",
[...]
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "headers": {
          "Accept": "application/json, text/plain, */*",
          "Content-Type": "application/octet-stream",
          "User-Agent": "axios/0.26.1",
          "Content-Length": 2800020
        },
        "method": "post",
        "url": "https://gateway.network.thegraph.com/partial-voucher",
        "data": {}
      },
      "status": 413
    }
  },
  "msg": "Failed to collect receipts in exchange for an on-chain query fee voucher"
}```

**Comment by madumas** [comment]
Actual limit seems to be around 18k vouchers or 2MB.

**Comment by tilacog** [comment]
@madumas Thanks for reporting this!
We will bump the Gateway's limit on that endpoint to accommodate 25k receipts. 

I'll close this issue when it goes live.

**Comment by tilacog** [comment]
Closing this because the changes just went live. 
Feel free to reopen if the problem persists.
