### ISSUE TITLE
v0.20.23 break "indexer-service"

### ISSUE THREAD

**Issue by matsuro-hadouken** [graphprotocol/indexer#815]
_Network: arbitrum-one_

After full js side of the indexer stack upgrade to v0.20.23 `indexer-service` trow errors and not able to process paid queries.

```json
{
    "level": 50,
    "time": 1698878802819,
    "err": {
        "type": "IndexerError",
        "message": "Failed to process paid query",
        "stack": "IndexerError: Failed to process paid query\n    at indexerError (/home/some-user/indexer/packages/indexer-common/dist/errors.js:173:12)\n    at /home/some-user/indexer/packages/indexer-service/dist/server/index.js:227:67\n    at Generator.throw (<anonymous>)\n    at rejected (/home/some-user/indexer/packages/indexer-service/dist/server/index.js:6:65)",
        "code": "IE032",
        "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie032",
        "cause": {
            "type": "Error",
            "message": "Unable to sign the query response attestation",
            "stack": "Error: Unable to sign the query response attestation\n    at QueryProcessor.<anonymous> (/home/some-user/indexer/packages/indexer-service/dist/queries.js:89:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/some-user/indexer/packages/indexer-service/dist/queries.js:5:58)",
            "status": 500
        }
    },
    "msg": "Failed to handle paid query"
}
```

additionally:

```json
{
    "level": 40,
    "time": 1698878854211,
    "name": "IndexerService",
    "component": "AllocationMonitor",
    "allocations": [],
    "err": {
        "type": "IndexerError",
        "message": "Failed to query indexer allocations",
        "stack": "IndexerError: Failed to query indexer allocations\n    at indexerError (/home/some-user/indexer/packages/indexer-common/dist/errors.js:173:12)\n    at /home/some-user/indexer/packages/indexer-service/dist/allocations.js:111:56\n    at Generator.next (<anonymous>)\n    at /home/some-user/indexer/packages/indexer-service/dist/allocations.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/some-user/indexer/packages/indexer-service/dist/allocations.js:4:12)\n    at refreshAllocations (/home/some-user/indexer/packages/indexer-service/dist/allocations.js:24:56)\n    at /home/some-user/indexer/node_modules/@graphprotocol/common-ts/dist/eventual/eventual.js:242:33\n    at Generator.next (<anonymous>)\n    at /home/some-user/indexer/node_modules/@graphprotocol/common-ts/dist/eventual/eventual.js:8:71",
        "code": "IE010",
        "cause": {
            "type": "GraphQLError",
            "message": "Syntax Error: Unexpected \"}\".",
            "stack": "GraphQLError: Syntax Error: Unexpected \"}\".\n    at syntaxError (/home/some-user/indexer/node_modules/graphql/error/syntaxError.js:15:10)\n    at Parser.unexpected (/home/some-user/indexer/node_modules/graphql/language/parser.js:1458:41)\n    at Parser.parseDefinition (/home/some-user/indexer/node_modules/graphql/language/parser.js:212:16)\n    at Parser.many (/home/some-user/indexer/node_modules/graphql/language/parser.js:1511:26)\n    at Parser.parseDocument (/home/some-user/indexer/node_modules/graphql/language/parser.js:122:25)\n    at Object.parse (/home/some-user/indexer/node_modules/graphql/language/parser.js:32:17)\n    at parseDocument (/home/some-user/indexer/node_modules/graphql-tag/lib/graphql-tag.umd.js:69:34)\n    at gql (/home/some-user/indexer/node_modules/graphql-tag/lib/graphql-tag.umd.js:98:16)\n    at /home/some-user/indexer/packages/indexer-service/dist/allocations.js:27:102\n    at Generator.next (<anonymous>)",
            "locations": [
                {
                    "line": 7,
                    "column": 9
                }
            ],
            "extensions": {}
        }
    },
    "msg": "Failed to query indexer allocations, keeping existing"
}
```

After multiple attempts to debug and fix this problem, I decided to revert to `v0.20.22` and all problems magically disappered.

There is no issues with agent or anything also, the only `indexer-service` is affected.

**Comment by alex-pakalniskis** [comment]
Sharing more comments from Discord:
https://discord.com/channels/438038660412342282/791444480628490290/1169694148702523482
> lots of IE10's & 32's.  before and after rolling back to .22 - Vince
