### ISSUE TITLE
indexer-agent: DB migration failure, `12-add-scalar-tap-table`

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#907]
Upon startup of indexer-agent I saw the following error when it tried to execute the 12th DB migration,`12-add-scalar-tap-table.js`. 

```
[13:30:09.556] DEBUG (IndexerAgent/7422): Checking if scalar_tap_receipts table exists
    tables: [
      "SequelizeMeta",
      "CostModels",
      "Actions",
      "allocation_receipts",
      "IndexingRules",
      "POIDisputes",
      "vouchers",
      "transfer_receipts",
      "transfers",
      "allocation_summaries"
    ]
[13:30:09.556] INFO (IndexerAgent/7422): Create scalar_tap_receipts
[13:30:09.606] DEBUG (IndexerAgent/7422): Create function and trigger using raw SQL
[13:30:09.659] INFO (IndexerAgent/7422): Add primary key
[13:30:09.664] INFO (IndexerAgent/7422): Remove one-to-one relationship between AllocationSummary and Voucher
[13:30:09.682] FATAL (IndexerAgent/7422): Failed to run database migrations
    err: {
      "cause": {
        "jse_cause": {
          "jse_cause": {
            "constraint": "voucher",
            "message": "Unknown constraint error",
            "name": "SequelizeUnknownConstraintError",
            "original": {
              "code": "42704",
              "file": "tablecmds.c",
              "length": 140,
              "line": "10934",
              "message": "constraint \"voucher\" of relation \"allocation_summaries\" does not exist",
              "name": "error",
              "routine": "ATExecDropConstraint",
              "severity": "ERROR",
              "sql": "ALTER TABLE \"allocation_summaries\" DROP CONSTRAINT \"voucher\"",
              "stack":
                  error: constraint "voucher" of relation "allocation_summaries" does not exist
                      at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                      at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                      at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                      at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                      at Socket.emit (node:events:514:28)
                      at Socket.emit (node:domain:488:12)
                      at addChunk (node:internal/streams/readable:545:12)
                      at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                      at Socket.Readable.push (node:internal/streams/readable:375:5)
                      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              "type": "DatabaseError"
            },
            "parameters": {},
            "parent": {
              "code": "42704",
              "file": "tablecmds.c",
              "length": 140,
              "line": "10934",
              "message": "constraint \"voucher\" of relation \"allocation_summaries\" does not exist",
              "name": "error",
              "routine": "ATExecDropConstraint",
              "severity": "ERROR",
              "sql": "ALTER TABLE \"allocation_summaries\" DROP CONSTRAINT \"voucher\"",
              "stack":
                  error: constraint "voucher" of relation "allocation_summaries" does not exist
                      at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                      at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                      at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                      at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                      at Socket.emit (node:events:514:28)
                      at Socket.emit (node:domain:488:12)
                      at addChunk (node:internal/streams/readable:545:12)
                      at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                      at Socket.Readable.push (node:internal/streams/readable:375:5)
                      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              "type": "DatabaseError"
            },
            "sql": "ALTER TABLE \"allocation_summaries\" DROP CONSTRAINT \"voucher\"",
            "stack":
                Error
                    at Query.run (/Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/dialects/postgres/query.js:76:25)
                    at /Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/sequelize.js:650:28
                    at processTicksAndRejections (node:internal/process/task_queues:95:5)
                    at async Object.up (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/db/migrations/12-add-scalar-tap-table.ts:180:5)
                    at async /Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:265:6
                    at async Umzug.runCommand (/Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:216:11)
                    at async run (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:561:5)
                    at async processArgumentsAndRun (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:60:5)
                    at async main (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:70:3)
            "table": "allocation_summaries",
            "type": "UnknownConstraintError"
          },
          "jse_info": {},
          "jse_shortmsg": "Original error",
          "message": "Original error: Unknown constraint error",
          "name": "VError",
          "stack":
              VError: Original error: Unknown constraint error
                  at Function.wrap (/Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:37:11)
                  at new MigrationError (/Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:54:24)
                  at /Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:267:12
                  at processTicksAndRejections (node:internal/process/task_queues:95:5)
                  at async Umzug.runCommand (/Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:216:11)
                  at async run (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:561:5)
                  at async processArgumentsAndRun (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:60:5)
                  at async main (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:70:3)
          "type": "VError"
        },
        "jse_info": {
          "context": {
            "graphNodeAdminEndpoint": "http://localhost:8020/",
            "logger": {
              "inner": "[Object]",
              "options": "[Object]"
            },
            "networkSpecifications": [
              "[Object]"
            ],
            "queryInterface": {
              "queryGenerator": "[Object]",
              "sequelize": "[Object]"
            }
          },
          "direction": "up",
          "name": "12-add-scalar-tap-table.js",
          "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/12-add-scalar-tap-table.js"
        },
        "jse_shortmsg": "Migration 12-add-scalar-tap-table.js (up) failed",
        "message": "Migration 12-add-scalar-tap-table.js (up) failed: Original error: Unknown constraint error",
        "name": "MigrationError",
        "stack":
            MigrationError: Migration 12-add-scalar-tap-table.js (up) failed: Original error: Unknown constraint error
                at /Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:267:12
                at processTicksAndRejections (node:internal/process/task_queues:95:5)
                at async Umzug.runCommand (/Users/ford/thegraph/workspaces/indexer/node_modules/umzug/src/umzug.ts:216:11)
                at async run (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:561:5)
                at async processArgumentsAndRun (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:60:5)
                at async main (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:70:3)
        "type": "MigrationError"
      },
      "code": "IE001",
      "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie001",
      "message": "Failed to run database migrations",
      "stack":
          IndexerError: Failed to run database migrations
              at indexerError (/Users/ford/thegraph/workspaces/indexer/packages/indexer-common/src/errors.ts:193:10)
              at run (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:564:24)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async processArgumentsAndRun (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:60:5)
              at async main (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/index.ts:70:3)
      "type": "IndexerError"
    }
```

**Comment by fordN** [comment]
It seems the migration was at least partially successful.  

Logs from a subsequent startup show the migration being retried, but the table and indices already existing. 

Relevant logs:
```
[13:32:24.417] DEBUG (IndexerAgent/7570): Migrations status
    pending: [
      {
        "name": "12-add-scalar-tap-table.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/12-add-scalar-tap-table.js"
      },
      {
        "name": "13-add-scalar-tap-deny-list.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/13-add-scalar-tap-deny-list.js"
      }
    ]
    executed: [
      {
        "name": "00-cost-model-variables-jsonb.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/00-cost-model-variables-jsonb.js"
      },
      {
        "name": "01-reset-state-channels.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/01-reset-state-channels.js"
      },
      {
        "name": "02-remove-state-channels.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/02-remove-state-channels.js"
      },
      {
        "name": "03-poi-disputes-add-subgraph-deployment-id.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/03-poi-disputes-add-subgraph-deployment-id.js"
      },
      {
        "name": "03-rename-receipts-table.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/03-rename-receipts-table.js"
      },
      {
        "name": "04-rename-fee-columns.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/04-rename-fee-columns.js"
      },
      {
        "name": "05-indexing-rules-add-subgraph-id.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/05-indexing-rules-add-subgraph-id.js"
      },
      {
        "name": "06-indexing-rules-add-max-lifetime.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/06-indexing-rules-add-max-lifetime.js"
      },
      {
        "name": "07-indexing-rules-add-require-supported.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/07-indexing-rules-add-require-supported.js"
      },
      {
        "name": "08-indexing-rules-add-auto-renewal.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/08-indexing-rules-add-auto-renewal.js"
      },
      {
        "name": "09-actions-expand-failure-reason-varchar.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/09-actions-expand-failure-reason-varchar.js"
      },
      {
        "name": "10-indexing-rules-add-safety.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/10-indexing-rules-add-safety.js"
      },
      {
        "name": "11-add-protocol-network-field.js",
        "path": "/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/dist/db/migrations/11-add-protocol-network-field.js"
      }
    ]
{ event: 'migrating', name: '12-add-scalar-tap-table.js' }
[13:32:24.427] DEBUG (IndexerAgent/7570): Checking if scalar_tap_receipts table exists
    tables: [
      "SequelizeMeta",
      "CostModels",
      "Actions",
      "allocation_receipts",
      "IndexingRules",
      "POIDisputes",
      "vouchers",
      "transfer_receipts",
      "transfers",
      "allocation_summaries",
      "scalar_tap_receipts_invalid",
      "scalar_tap_receipts",
      "scalar_tap_ravs"
    ]
[13:32:24.427] DEBUG (IndexerAgent/7570): scalar_tap_receipts already exist, migration not necessary
[13:32:24.427] DEBUG (IndexerAgent/7570): Create function and trigger using raw SQL
[13:32:24.428] INFO (IndexerAgent/7570): scalar_tap_receipts_invalid already exist, migration not necessary
[13:32:24.440] WARN (IndexerAgent/7570): Unhandled promise rejection
    err: {
      "type": "IndexerError",
      "message": "Unhandled promise rejection",
      "stack":
          IndexerError: Unhandled promise rejection
              at indexerError (/Users/ford/thegraph/workspaces/indexer/packages/indexer-common/src/errors.ts:193:10)
              at process.<anonymous> (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:478:24)
              at process.emit (node:events:514:28)
              at process.emit (node:domain:488:12)
              at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/ford/.nvm/versions/node/v20.10.0/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
              at emit (node:internal/process/promises:150:20)
              at processPromiseRejections (node:internal/process/promises:284:27)
              at processTicksAndRejections (node:internal/process/task_queues:96:32)
      "code": "IE035",
      "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie035",
      "cause": {
        "type": "DatabaseError",
        "message": "relation \"scalar_tap_receipts_allocation_id_idx\" already exists",
        "stack":
            Error
                at Query.run (/Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/dialects/postgres/query.js:76:25)
                at /Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/sequelize.js:650:28
                at processTicksAndRejections (node:internal/process/task_queues:95:5)
                at async PostgresQueryInterface.addIndex (/Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/dialects/abstract/query-interface.js:586:12)
        "name": "SequelizeDatabaseError",
        "parent": {
          "type": "DatabaseError",
          "message": "relation \"scalar_tap_receipts_allocation_id_idx\" already exists",
          "stack":
              error: relation "scalar_tap_receipts_allocation_id_idx" already exists
                  at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                  at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                  at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                  at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                  at Socket.emit (node:events:514:28)
                  at Socket.emit (node:domain:488:12)
                  at addChunk (node:internal/streams/readable:545:12)
                  at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                  at Socket.Readable.push (node:internal/streams/readable:375:5)
                  at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
          "length": 119,
          "name": "error",
          "severity": "ERROR",
          "code": "42P07",
          "file": "index.c",
          "line": "866",
          "routine": "index_create",
          "sql": "CREATE INDEX \"scalar_tap_receipts_allocation_id_idx\" ON \"scalar_tap_receipts\" (\"allocation_id\")"
        },
        "original": {
          "type": "DatabaseError",
          "message": "relation \"scalar_tap_receipts_allocation_id_idx\" already exists",
          "stack":
              error: relation "scalar_tap_receipts_allocation_id_idx" already exists
                  at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                  at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                  at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                  at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                  at Socket.emit (node:events:514:28)
                  at Socket.emit (node:domain:488:12)
                  at addChunk (node:internal/streams/readable:545:12)
                  at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                  at Socket.Readable.push (node:internal/streams/readable:375:5)
                  at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
          "length": 119,
          "name": "error",
          "severity": "ERROR",
          "code": "42P07",
          "file": "index.c",
          "line": "866",
          "routine": "index_create",
          "sql": "CREATE INDEX \"scalar_tap_receipts_allocation_id_idx\" ON \"scalar_tap_receipts\" (\"allocation_id\")"
        },
        "sql": "CREATE INDEX \"scalar_tap_receipts_allocation_id_idx\" ON \"scalar_tap_receipts\" (\"allocation_id\")",
        "parameters": {}
      }
    }
[13:32:24.450] WARN (IndexerAgent/7570): Unhandled promise rejection
    err: {
      "type": "IndexerError",
      "message": "Unhandled promise rejection",
      "stack":
          IndexerError: Unhandled promise rejection
              at indexerError (/Users/ford/thegraph/workspaces/indexer/packages/indexer-common/src/errors.ts:193:10)
              at process.<anonymous> (/Users/ford/thegraph/workspaces/indexer/packages/indexer-agent/src/commands/start.ts:478:24)
              at process.emit (node:events:514:28)
              at process.emit (node:domain:488:12)
              at process.emit.sharedData.processEmitHook.installedValue [as emit] (/Users/ford/.nvm/versions/node/v20.10.0/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:745:40)
              at emit (node:internal/process/promises:150:20)
              at processPromiseRejections (node:internal/process/promises:284:27)
              at processTicksAndRejections (node:internal/process/task_queues:96:32)
      "code": "IE035",
      "explanation": "https://github.com/graphprotocol/indexer/blob/main/docs/errors.md#ie035",
      "cause": {
        "type": "DatabaseError",
        "message": "relation \"scalar_tap_receipts_timestamp_ns_idx\" already exists",
        "stack":
            Error
                at Query.run (/Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/dialects/postgres/query.js:76:25)
                at /Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/sequelize.js:650:28
                at processTicksAndRejections (node:internal/process/task_queues:95:5)
                at async PostgresQueryInterface.addIndex (/Users/ford/thegraph/workspaces/indexer/node_modules/sequelize/src/dialects/abstract/query-interface.js:586:12)
        "name": "SequelizeDatabaseError",
        "parent": {
          "type": "DatabaseError",
          "message": "relation \"scalar_tap_receipts_timestamp_ns_idx\" already exists",
          "stack":
              error: relation "scalar_tap_receipts_timestamp_ns_idx" already exists
                  at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                  at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                  at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                  at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                  at Socket.emit (node:events:514:28)
                  at Socket.emit (node:domain:488:12)
                  at addChunk (node:internal/streams/readable:545:12)
                  at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                  at Socket.Readable.push (node:internal/streams/readable:375:5)
                  at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
          "length": 118,
          "name": "error",
          "severity": "ERROR",
          "code": "42P07",
          "file": "index.c",
          "line": "866",
          "routine": "index_create",
          "sql": "CREATE INDEX \"scalar_tap_receipts_timestamp_ns_idx\" ON \"scalar_tap_receipts\" (\"timestamp_ns\")"
        },
        "original": {
          "type": "DatabaseError",
          "message": "relation \"scalar_tap_receipts_timestamp_ns_idx\" already exists",
          "stack":
              error: relation "scalar_tap_receipts_timestamp_ns_idx" already exists
                  at Parser.parseErrorMessage (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:369:69)
                  at Parser.handlePacket (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:188:21)
                  at Parser.parse (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/parser.ts:103:30)
                  at Socket.<anonymous> (/Users/ford/thegraph/workspaces/indexer/node_modules/pg-protocol/src/index.ts:7:48)
                  at Socket.emit (node:events:514:28)
                  at Socket.emit (node:domain:488:12)
                  at addChunk (node:internal/streams/readable:545:12)
                  at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
                  at Socket.Readable.push (node:internal/streams/readable:375:5)
                  at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
          "length": 118,
          "name": "error",
          "severity": "ERROR",
          "code": "42P07",
          "file": "index.c",
          "line": "866",
          "routine": "index_create",
          "sql": "CREATE INDEX \"scalar_tap_receipts_timestamp_ns_idx\" ON \"scalar_tap_receipts\" (\"timestamp_ns\")"
        },
        "sql": "CREATE INDEX \"scalar_tap_receipts_timestamp_ns_idx\" ON \"scalar_tap_receipts\" (\"timestamp_ns\")",
        "parameters": {}
      }
    }
{
  event: 'migrated',
  name: '12-add-scalar-tap-table.js',
  durationSeconds: 0.036
}
{ event: 'migrating', name: '13-add-scalar-tap-deny-list.js' }
[13:32:24.462] DEBUG (IndexerAgent/7570): Checking if scalar_tap_denylist table exists
    tables: [
      "SequelizeMeta",
      "CostModels",
      "Actions",
      "allocation_receipts",
      "IndexingRules",
      "POIDisputes",
      "vouchers",
      "transfer_receipts",
      "transfers",
      "allocation_summaries",
      "scalar_tap_receipts_invalid",
      "scalar_tap_receipts",
      "scalar_tap_ravs"
    ]
[13:32:24.462] INFO (IndexerAgent/7570): Create scalar_tap_denylist
{
  event: 'migrated',
  name: '13-add-scalar-tap-deny-list.js',
  durationSeconds: 0.018
}
[13:32:24.477] INFO (IndexerAgent/7570): Successfully ran database migrations
[13:32:24.477] INFO (IndexerAgent/7570): Sync database models
[13:32:24.609] INFO (IndexerAgent/7570): Successfully synced database models
```
