### ISSUE TITLE
Bug: Seg fault starting Node processes

### ISSUE THREAD

**Issue by fordN** [graphprotocol/indexer#972]
Observed by several indexers when trying to run `indexer-agent` or `indexer-service`.

The error appears to be coming from `neon` libraries.

**Comment by dwerner** [comment]
```
(No debugging symbols found in /usr/bin/env)
(gdb) run
Starting program: /usr/bin/env node /home/pops/git/indexer/packages/indexer-service/bin/graph-indexer-service
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
process 1468493 is executing new program: /usr/bin/node
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7a47640 (LWP 1468514)]
[New Thread 0x7ffff7246640 (LWP 1468515)]
[New Thread 0x7ffff6a45640 (LWP 1468516)]
[New Thread 0x7ffff6244640 (LWP 1468517)]
[New Thread 0x7ffff5a43640 (LWP 1468518)]
[New Thread 0x7ffff5242640 (LWP 1468519)]

Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff4c3dd83 in neon::object::class::ClassMap::get () from /home/pops/git/indexer/packages/indexer-native/binary/index.node
(gdb) bt 0x00007ffff4c3dd83
#0  0x00007ffff4c3dd83 in neon::object::class::ClassMap::get () from /home/pops/git/indexer/packages/indexer-native/binary/index.node
#1  0x00007ffff4c0fdf8 in neon::object::class::Class::constructor () from /home/pops/git/indexer/packages/indexer-native/binary/index.node
#2  0x00007ffff4c10326 in indexer_native::__LOAD_NEON_MODULE::__init_neon_module () from /home/pops/git/indexer/packages/indexer-native/binary/index.node
#3  0x00007ffff4c3ec4d in neon::context::internal::initialize_module () from /home/pops/git/indexer/packages/indexer-native/binary/index.node
#4  0x0000000000ad59e7 in std::_Function_handler<bool (node::binding::DLib*), node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::{lambda(node::binding::DLib*)#1}>::_M_invoke(std::_Any_data const&, node::binding::DLib*&&) ()
#5  0x0000000000a8960e in node::Environment::TryLoadAddon(char const*, int, std::function<bool (node::binding::DLib*)> const&) ()
#6  0x0000000000ad4e90 in node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) ()
#7  0x0000000000d3df8e in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#8  0x0000000000d3f3af in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) ()
#9  0x00000000015d9f39 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit ()
#10 0x000000000156c90a in Builtins_InterpreterEntryTrampoline ()
#11 0x00002a54df7c1599 in ?? ()
#12 0x000025a54e147789 in ?? ()
```
